/********************************************************************************
** Form generated from reading UI file 'currentlydue.ui'
**
** Created by: Qt User Interface Compiler version 6.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CURRENTLYDUE_H
#define UI_CURRENTLYDUE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CurrentlyDue
{
public:
    QAction *actionChange_Week;
    QWidget *centralwidget;
    QLabel *label;
    QTableWidget *tableWidget;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QLabel *label_2;
    QLabel *label_3;
    QDateEdit *dateEdit;
    QDateEdit *dateEdit_2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *collectionTotal;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *CurrentlyDue)
    {
        if (CurrentlyDue->objectName().isEmpty())
            CurrentlyDue->setObjectName("CurrentlyDue");
        CurrentlyDue->resize(880, 1080);
        actionChange_Week = new QAction(CurrentlyDue);
        actionChange_Week->setObjectName("actionChange_Week");
        centralwidget = new QWidget(CurrentlyDue);
        centralwidget->setObjectName("centralwidget");
        label = new QLabel(centralwidget);
        label->setObjectName("label");
        label->setGeometry(QRect(40, 10, 171, 91));
        tableWidget = new QTableWidget(centralwidget);
        if (tableWidget->columnCount() < 8)
            tableWidget->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(7, __qtablewidgetitem7);
        if (tableWidget->rowCount() < 30)
            tableWidget->setRowCount(30);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(6, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(7, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(8, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(9, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(10, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(11, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(12, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(13, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(14, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(15, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(16, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(17, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(18, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(19, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(20, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(21, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(22, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(23, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(24, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(25, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(26, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(27, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(28, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(29, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget->setItem(0, 1, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWidget->setItem(0, 2, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget->setItem(0, 3, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWidget->setItem(0, 4, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget->setItem(0, 5, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWidget->setItem(0, 6, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWidget->setItem(0, 7, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableWidget->setItem(1, 1, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWidget->setItem(1, 2, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWidget->setItem(1, 3, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWidget->setItem(1, 4, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tableWidget->setItem(1, 5, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tableWidget->setItem(1, 6, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tableWidget->setItem(1, 7, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableWidget->setItem(2, 1, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableWidget->setItem(2, 2, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableWidget->setItem(2, 3, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableWidget->setItem(2, 4, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        tableWidget->setItem(2, 5, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        tableWidget->setItem(2, 6, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        tableWidget->setItem(2, 7, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        tableWidget->setItem(3, 1, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        tableWidget->setItem(3, 2, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        tableWidget->setItem(3, 3, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        tableWidget->setItem(3, 4, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        tableWidget->setItem(3, 5, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        tableWidget->setItem(3, 6, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        tableWidget->setItem(3, 7, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        tableWidget->setItem(4, 1, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        tableWidget->setItem(4, 2, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        tableWidget->setItem(4, 3, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        tableWidget->setItem(4, 4, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        tableWidget->setItem(4, 5, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        tableWidget->setItem(4, 6, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        tableWidget->setItem(4, 7, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        tableWidget->setItem(5, 1, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        tableWidget->setItem(5, 2, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        tableWidget->setItem(5, 3, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        tableWidget->setItem(5, 4, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        tableWidget->setItem(5, 5, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        tableWidget->setItem(5, 6, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        tableWidget->setItem(5, 7, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        tableWidget->setItem(6, 1, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        tableWidget->setItem(6, 2, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        tableWidget->setItem(6, 3, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        tableWidget->setItem(6, 4, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        tableWidget->setItem(6, 5, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        tableWidget->setItem(6, 6, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        tableWidget->setItem(6, 7, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        tableWidget->setItem(7, 1, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        tableWidget->setItem(7, 2, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        tableWidget->setItem(7, 3, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        tableWidget->setItem(7, 4, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        tableWidget->setItem(7, 5, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        tableWidget->setItem(7, 6, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        tableWidget->setItem(7, 7, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        tableWidget->setItem(8, 1, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        tableWidget->setItem(8, 2, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        tableWidget->setItem(8, 3, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        tableWidget->setItem(8, 4, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        tableWidget->setItem(8, 5, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        tableWidget->setItem(8, 6, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        tableWidget->setItem(8, 7, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        tableWidget->setItem(9, 1, __qtablewidgetitem101);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        tableWidget->setItem(9, 2, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        tableWidget->setItem(9, 3, __qtablewidgetitem103);
        QTableWidgetItem *__qtablewidgetitem104 = new QTableWidgetItem();
        tableWidget->setItem(9, 4, __qtablewidgetitem104);
        QTableWidgetItem *__qtablewidgetitem105 = new QTableWidgetItem();
        tableWidget->setItem(9, 5, __qtablewidgetitem105);
        QTableWidgetItem *__qtablewidgetitem106 = new QTableWidgetItem();
        tableWidget->setItem(9, 6, __qtablewidgetitem106);
        QTableWidgetItem *__qtablewidgetitem107 = new QTableWidgetItem();
        tableWidget->setItem(9, 7, __qtablewidgetitem107);
        QTableWidgetItem *__qtablewidgetitem108 = new QTableWidgetItem();
        tableWidget->setItem(10, 1, __qtablewidgetitem108);
        QTableWidgetItem *__qtablewidgetitem109 = new QTableWidgetItem();
        tableWidget->setItem(10, 2, __qtablewidgetitem109);
        QTableWidgetItem *__qtablewidgetitem110 = new QTableWidgetItem();
        tableWidget->setItem(10, 3, __qtablewidgetitem110);
        QTableWidgetItem *__qtablewidgetitem111 = new QTableWidgetItem();
        tableWidget->setItem(10, 4, __qtablewidgetitem111);
        QTableWidgetItem *__qtablewidgetitem112 = new QTableWidgetItem();
        tableWidget->setItem(10, 5, __qtablewidgetitem112);
        QTableWidgetItem *__qtablewidgetitem113 = new QTableWidgetItem();
        tableWidget->setItem(10, 6, __qtablewidgetitem113);
        QTableWidgetItem *__qtablewidgetitem114 = new QTableWidgetItem();
        tableWidget->setItem(10, 7, __qtablewidgetitem114);
        QTableWidgetItem *__qtablewidgetitem115 = new QTableWidgetItem();
        tableWidget->setItem(11, 1, __qtablewidgetitem115);
        QTableWidgetItem *__qtablewidgetitem116 = new QTableWidgetItem();
        tableWidget->setItem(11, 2, __qtablewidgetitem116);
        QTableWidgetItem *__qtablewidgetitem117 = new QTableWidgetItem();
        tableWidget->setItem(11, 3, __qtablewidgetitem117);
        QTableWidgetItem *__qtablewidgetitem118 = new QTableWidgetItem();
        tableWidget->setItem(11, 4, __qtablewidgetitem118);
        QTableWidgetItem *__qtablewidgetitem119 = new QTableWidgetItem();
        tableWidget->setItem(11, 5, __qtablewidgetitem119);
        QTableWidgetItem *__qtablewidgetitem120 = new QTableWidgetItem();
        tableWidget->setItem(11, 6, __qtablewidgetitem120);
        QTableWidgetItem *__qtablewidgetitem121 = new QTableWidgetItem();
        tableWidget->setItem(11, 7, __qtablewidgetitem121);
        QTableWidgetItem *__qtablewidgetitem122 = new QTableWidgetItem();
        tableWidget->setItem(12, 1, __qtablewidgetitem122);
        QTableWidgetItem *__qtablewidgetitem123 = new QTableWidgetItem();
        tableWidget->setItem(12, 2, __qtablewidgetitem123);
        QTableWidgetItem *__qtablewidgetitem124 = new QTableWidgetItem();
        tableWidget->setItem(12, 3, __qtablewidgetitem124);
        QTableWidgetItem *__qtablewidgetitem125 = new QTableWidgetItem();
        tableWidget->setItem(12, 4, __qtablewidgetitem125);
        QTableWidgetItem *__qtablewidgetitem126 = new QTableWidgetItem();
        tableWidget->setItem(12, 5, __qtablewidgetitem126);
        QTableWidgetItem *__qtablewidgetitem127 = new QTableWidgetItem();
        tableWidget->setItem(12, 6, __qtablewidgetitem127);
        QTableWidgetItem *__qtablewidgetitem128 = new QTableWidgetItem();
        tableWidget->setItem(12, 7, __qtablewidgetitem128);
        QTableWidgetItem *__qtablewidgetitem129 = new QTableWidgetItem();
        tableWidget->setItem(13, 1, __qtablewidgetitem129);
        QTableWidgetItem *__qtablewidgetitem130 = new QTableWidgetItem();
        tableWidget->setItem(13, 2, __qtablewidgetitem130);
        QTableWidgetItem *__qtablewidgetitem131 = new QTableWidgetItem();
        tableWidget->setItem(13, 3, __qtablewidgetitem131);
        QTableWidgetItem *__qtablewidgetitem132 = new QTableWidgetItem();
        tableWidget->setItem(13, 4, __qtablewidgetitem132);
        QTableWidgetItem *__qtablewidgetitem133 = new QTableWidgetItem();
        tableWidget->setItem(13, 5, __qtablewidgetitem133);
        QTableWidgetItem *__qtablewidgetitem134 = new QTableWidgetItem();
        tableWidget->setItem(13, 6, __qtablewidgetitem134);
        QTableWidgetItem *__qtablewidgetitem135 = new QTableWidgetItem();
        tableWidget->setItem(13, 7, __qtablewidgetitem135);
        QTableWidgetItem *__qtablewidgetitem136 = new QTableWidgetItem();
        tableWidget->setItem(14, 1, __qtablewidgetitem136);
        QTableWidgetItem *__qtablewidgetitem137 = new QTableWidgetItem();
        tableWidget->setItem(14, 2, __qtablewidgetitem137);
        QTableWidgetItem *__qtablewidgetitem138 = new QTableWidgetItem();
        tableWidget->setItem(14, 3, __qtablewidgetitem138);
        QTableWidgetItem *__qtablewidgetitem139 = new QTableWidgetItem();
        tableWidget->setItem(14, 4, __qtablewidgetitem139);
        QTableWidgetItem *__qtablewidgetitem140 = new QTableWidgetItem();
        tableWidget->setItem(14, 5, __qtablewidgetitem140);
        QTableWidgetItem *__qtablewidgetitem141 = new QTableWidgetItem();
        tableWidget->setItem(14, 6, __qtablewidgetitem141);
        QTableWidgetItem *__qtablewidgetitem142 = new QTableWidgetItem();
        tableWidget->setItem(14, 7, __qtablewidgetitem142);
        QTableWidgetItem *__qtablewidgetitem143 = new QTableWidgetItem();
        tableWidget->setItem(15, 1, __qtablewidgetitem143);
        QTableWidgetItem *__qtablewidgetitem144 = new QTableWidgetItem();
        tableWidget->setItem(15, 2, __qtablewidgetitem144);
        QTableWidgetItem *__qtablewidgetitem145 = new QTableWidgetItem();
        tableWidget->setItem(15, 3, __qtablewidgetitem145);
        QTableWidgetItem *__qtablewidgetitem146 = new QTableWidgetItem();
        tableWidget->setItem(15, 4, __qtablewidgetitem146);
        QTableWidgetItem *__qtablewidgetitem147 = new QTableWidgetItem();
        tableWidget->setItem(15, 5, __qtablewidgetitem147);
        QTableWidgetItem *__qtablewidgetitem148 = new QTableWidgetItem();
        tableWidget->setItem(15, 6, __qtablewidgetitem148);
        QTableWidgetItem *__qtablewidgetitem149 = new QTableWidgetItem();
        tableWidget->setItem(15, 7, __qtablewidgetitem149);
        QTableWidgetItem *__qtablewidgetitem150 = new QTableWidgetItem();
        tableWidget->setItem(16, 1, __qtablewidgetitem150);
        QTableWidgetItem *__qtablewidgetitem151 = new QTableWidgetItem();
        tableWidget->setItem(16, 2, __qtablewidgetitem151);
        QTableWidgetItem *__qtablewidgetitem152 = new QTableWidgetItem();
        tableWidget->setItem(16, 3, __qtablewidgetitem152);
        QTableWidgetItem *__qtablewidgetitem153 = new QTableWidgetItem();
        tableWidget->setItem(16, 4, __qtablewidgetitem153);
        QTableWidgetItem *__qtablewidgetitem154 = new QTableWidgetItem();
        tableWidget->setItem(16, 5, __qtablewidgetitem154);
        QTableWidgetItem *__qtablewidgetitem155 = new QTableWidgetItem();
        tableWidget->setItem(16, 6, __qtablewidgetitem155);
        QTableWidgetItem *__qtablewidgetitem156 = new QTableWidgetItem();
        tableWidget->setItem(16, 7, __qtablewidgetitem156);
        QTableWidgetItem *__qtablewidgetitem157 = new QTableWidgetItem();
        tableWidget->setItem(17, 1, __qtablewidgetitem157);
        QTableWidgetItem *__qtablewidgetitem158 = new QTableWidgetItem();
        tableWidget->setItem(17, 2, __qtablewidgetitem158);
        QTableWidgetItem *__qtablewidgetitem159 = new QTableWidgetItem();
        tableWidget->setItem(17, 3, __qtablewidgetitem159);
        QTableWidgetItem *__qtablewidgetitem160 = new QTableWidgetItem();
        tableWidget->setItem(17, 4, __qtablewidgetitem160);
        QTableWidgetItem *__qtablewidgetitem161 = new QTableWidgetItem();
        tableWidget->setItem(17, 5, __qtablewidgetitem161);
        QTableWidgetItem *__qtablewidgetitem162 = new QTableWidgetItem();
        tableWidget->setItem(17, 6, __qtablewidgetitem162);
        QTableWidgetItem *__qtablewidgetitem163 = new QTableWidgetItem();
        tableWidget->setItem(17, 7, __qtablewidgetitem163);
        QTableWidgetItem *__qtablewidgetitem164 = new QTableWidgetItem();
        tableWidget->setItem(18, 1, __qtablewidgetitem164);
        QTableWidgetItem *__qtablewidgetitem165 = new QTableWidgetItem();
        tableWidget->setItem(18, 2, __qtablewidgetitem165);
        QTableWidgetItem *__qtablewidgetitem166 = new QTableWidgetItem();
        tableWidget->setItem(18, 3, __qtablewidgetitem166);
        QTableWidgetItem *__qtablewidgetitem167 = new QTableWidgetItem();
        tableWidget->setItem(18, 4, __qtablewidgetitem167);
        QTableWidgetItem *__qtablewidgetitem168 = new QTableWidgetItem();
        tableWidget->setItem(18, 5, __qtablewidgetitem168);
        QTableWidgetItem *__qtablewidgetitem169 = new QTableWidgetItem();
        tableWidget->setItem(18, 6, __qtablewidgetitem169);
        QTableWidgetItem *__qtablewidgetitem170 = new QTableWidgetItem();
        tableWidget->setItem(18, 7, __qtablewidgetitem170);
        QTableWidgetItem *__qtablewidgetitem171 = new QTableWidgetItem();
        tableWidget->setItem(19, 1, __qtablewidgetitem171);
        QTableWidgetItem *__qtablewidgetitem172 = new QTableWidgetItem();
        tableWidget->setItem(19, 2, __qtablewidgetitem172);
        QTableWidgetItem *__qtablewidgetitem173 = new QTableWidgetItem();
        tableWidget->setItem(19, 3, __qtablewidgetitem173);
        QTableWidgetItem *__qtablewidgetitem174 = new QTableWidgetItem();
        tableWidget->setItem(19, 4, __qtablewidgetitem174);
        QTableWidgetItem *__qtablewidgetitem175 = new QTableWidgetItem();
        tableWidget->setItem(19, 5, __qtablewidgetitem175);
        QTableWidgetItem *__qtablewidgetitem176 = new QTableWidgetItem();
        tableWidget->setItem(19, 6, __qtablewidgetitem176);
        QTableWidgetItem *__qtablewidgetitem177 = new QTableWidgetItem();
        tableWidget->setItem(19, 7, __qtablewidgetitem177);
        QTableWidgetItem *__qtablewidgetitem178 = new QTableWidgetItem();
        tableWidget->setItem(20, 1, __qtablewidgetitem178);
        QTableWidgetItem *__qtablewidgetitem179 = new QTableWidgetItem();
        tableWidget->setItem(20, 2, __qtablewidgetitem179);
        QTableWidgetItem *__qtablewidgetitem180 = new QTableWidgetItem();
        tableWidget->setItem(20, 3, __qtablewidgetitem180);
        QTableWidgetItem *__qtablewidgetitem181 = new QTableWidgetItem();
        tableWidget->setItem(20, 4, __qtablewidgetitem181);
        QTableWidgetItem *__qtablewidgetitem182 = new QTableWidgetItem();
        tableWidget->setItem(20, 5, __qtablewidgetitem182);
        QTableWidgetItem *__qtablewidgetitem183 = new QTableWidgetItem();
        tableWidget->setItem(20, 6, __qtablewidgetitem183);
        QTableWidgetItem *__qtablewidgetitem184 = new QTableWidgetItem();
        tableWidget->setItem(20, 7, __qtablewidgetitem184);
        QTableWidgetItem *__qtablewidgetitem185 = new QTableWidgetItem();
        tableWidget->setItem(21, 1, __qtablewidgetitem185);
        QTableWidgetItem *__qtablewidgetitem186 = new QTableWidgetItem();
        tableWidget->setItem(21, 2, __qtablewidgetitem186);
        QTableWidgetItem *__qtablewidgetitem187 = new QTableWidgetItem();
        tableWidget->setItem(21, 3, __qtablewidgetitem187);
        QTableWidgetItem *__qtablewidgetitem188 = new QTableWidgetItem();
        tableWidget->setItem(21, 4, __qtablewidgetitem188);
        QTableWidgetItem *__qtablewidgetitem189 = new QTableWidgetItem();
        tableWidget->setItem(21, 5, __qtablewidgetitem189);
        QTableWidgetItem *__qtablewidgetitem190 = new QTableWidgetItem();
        tableWidget->setItem(21, 6, __qtablewidgetitem190);
        QTableWidgetItem *__qtablewidgetitem191 = new QTableWidgetItem();
        tableWidget->setItem(21, 7, __qtablewidgetitem191);
        QTableWidgetItem *__qtablewidgetitem192 = new QTableWidgetItem();
        tableWidget->setItem(22, 1, __qtablewidgetitem192);
        QTableWidgetItem *__qtablewidgetitem193 = new QTableWidgetItem();
        tableWidget->setItem(22, 2, __qtablewidgetitem193);
        QTableWidgetItem *__qtablewidgetitem194 = new QTableWidgetItem();
        tableWidget->setItem(22, 3, __qtablewidgetitem194);
        QTableWidgetItem *__qtablewidgetitem195 = new QTableWidgetItem();
        tableWidget->setItem(22, 4, __qtablewidgetitem195);
        QTableWidgetItem *__qtablewidgetitem196 = new QTableWidgetItem();
        tableWidget->setItem(22, 5, __qtablewidgetitem196);
        QTableWidgetItem *__qtablewidgetitem197 = new QTableWidgetItem();
        tableWidget->setItem(22, 6, __qtablewidgetitem197);
        QTableWidgetItem *__qtablewidgetitem198 = new QTableWidgetItem();
        tableWidget->setItem(22, 7, __qtablewidgetitem198);
        QTableWidgetItem *__qtablewidgetitem199 = new QTableWidgetItem();
        tableWidget->setItem(23, 1, __qtablewidgetitem199);
        QTableWidgetItem *__qtablewidgetitem200 = new QTableWidgetItem();
        tableWidget->setItem(23, 2, __qtablewidgetitem200);
        QTableWidgetItem *__qtablewidgetitem201 = new QTableWidgetItem();
        tableWidget->setItem(23, 3, __qtablewidgetitem201);
        QTableWidgetItem *__qtablewidgetitem202 = new QTableWidgetItem();
        tableWidget->setItem(23, 4, __qtablewidgetitem202);
        QTableWidgetItem *__qtablewidgetitem203 = new QTableWidgetItem();
        tableWidget->setItem(23, 5, __qtablewidgetitem203);
        QTableWidgetItem *__qtablewidgetitem204 = new QTableWidgetItem();
        tableWidget->setItem(23, 6, __qtablewidgetitem204);
        QTableWidgetItem *__qtablewidgetitem205 = new QTableWidgetItem();
        tableWidget->setItem(23, 7, __qtablewidgetitem205);
        QTableWidgetItem *__qtablewidgetitem206 = new QTableWidgetItem();
        tableWidget->setItem(24, 1, __qtablewidgetitem206);
        QTableWidgetItem *__qtablewidgetitem207 = new QTableWidgetItem();
        tableWidget->setItem(24, 2, __qtablewidgetitem207);
        QTableWidgetItem *__qtablewidgetitem208 = new QTableWidgetItem();
        tableWidget->setItem(24, 3, __qtablewidgetitem208);
        QTableWidgetItem *__qtablewidgetitem209 = new QTableWidgetItem();
        tableWidget->setItem(24, 4, __qtablewidgetitem209);
        QTableWidgetItem *__qtablewidgetitem210 = new QTableWidgetItem();
        tableWidget->setItem(24, 5, __qtablewidgetitem210);
        QTableWidgetItem *__qtablewidgetitem211 = new QTableWidgetItem();
        tableWidget->setItem(24, 6, __qtablewidgetitem211);
        QTableWidgetItem *__qtablewidgetitem212 = new QTableWidgetItem();
        tableWidget->setItem(24, 7, __qtablewidgetitem212);
        QTableWidgetItem *__qtablewidgetitem213 = new QTableWidgetItem();
        tableWidget->setItem(25, 1, __qtablewidgetitem213);
        QTableWidgetItem *__qtablewidgetitem214 = new QTableWidgetItem();
        tableWidget->setItem(25, 2, __qtablewidgetitem214);
        QTableWidgetItem *__qtablewidgetitem215 = new QTableWidgetItem();
        tableWidget->setItem(25, 3, __qtablewidgetitem215);
        QTableWidgetItem *__qtablewidgetitem216 = new QTableWidgetItem();
        tableWidget->setItem(25, 4, __qtablewidgetitem216);
        QTableWidgetItem *__qtablewidgetitem217 = new QTableWidgetItem();
        tableWidget->setItem(25, 5, __qtablewidgetitem217);
        QTableWidgetItem *__qtablewidgetitem218 = new QTableWidgetItem();
        tableWidget->setItem(25, 6, __qtablewidgetitem218);
        QTableWidgetItem *__qtablewidgetitem219 = new QTableWidgetItem();
        tableWidget->setItem(25, 7, __qtablewidgetitem219);
        QTableWidgetItem *__qtablewidgetitem220 = new QTableWidgetItem();
        tableWidget->setItem(26, 1, __qtablewidgetitem220);
        QTableWidgetItem *__qtablewidgetitem221 = new QTableWidgetItem();
        tableWidget->setItem(26, 2, __qtablewidgetitem221);
        QTableWidgetItem *__qtablewidgetitem222 = new QTableWidgetItem();
        tableWidget->setItem(26, 3, __qtablewidgetitem222);
        QTableWidgetItem *__qtablewidgetitem223 = new QTableWidgetItem();
        tableWidget->setItem(26, 4, __qtablewidgetitem223);
        QTableWidgetItem *__qtablewidgetitem224 = new QTableWidgetItem();
        tableWidget->setItem(26, 5, __qtablewidgetitem224);
        QTableWidgetItem *__qtablewidgetitem225 = new QTableWidgetItem();
        tableWidget->setItem(26, 6, __qtablewidgetitem225);
        QTableWidgetItem *__qtablewidgetitem226 = new QTableWidgetItem();
        tableWidget->setItem(26, 7, __qtablewidgetitem226);
        QTableWidgetItem *__qtablewidgetitem227 = new QTableWidgetItem();
        tableWidget->setItem(27, 1, __qtablewidgetitem227);
        QTableWidgetItem *__qtablewidgetitem228 = new QTableWidgetItem();
        tableWidget->setItem(27, 2, __qtablewidgetitem228);
        QTableWidgetItem *__qtablewidgetitem229 = new QTableWidgetItem();
        tableWidget->setItem(27, 3, __qtablewidgetitem229);
        QTableWidgetItem *__qtablewidgetitem230 = new QTableWidgetItem();
        tableWidget->setItem(27, 4, __qtablewidgetitem230);
        QTableWidgetItem *__qtablewidgetitem231 = new QTableWidgetItem();
        tableWidget->setItem(27, 5, __qtablewidgetitem231);
        QTableWidgetItem *__qtablewidgetitem232 = new QTableWidgetItem();
        tableWidget->setItem(27, 6, __qtablewidgetitem232);
        QTableWidgetItem *__qtablewidgetitem233 = new QTableWidgetItem();
        tableWidget->setItem(27, 7, __qtablewidgetitem233);
        QTableWidgetItem *__qtablewidgetitem234 = new QTableWidgetItem();
        tableWidget->setItem(28, 1, __qtablewidgetitem234);
        QTableWidgetItem *__qtablewidgetitem235 = new QTableWidgetItem();
        tableWidget->setItem(28, 2, __qtablewidgetitem235);
        QTableWidgetItem *__qtablewidgetitem236 = new QTableWidgetItem();
        tableWidget->setItem(28, 3, __qtablewidgetitem236);
        QTableWidgetItem *__qtablewidgetitem237 = new QTableWidgetItem();
        tableWidget->setItem(28, 4, __qtablewidgetitem237);
        QTableWidgetItem *__qtablewidgetitem238 = new QTableWidgetItem();
        tableWidget->setItem(28, 5, __qtablewidgetitem238);
        QTableWidgetItem *__qtablewidgetitem239 = new QTableWidgetItem();
        tableWidget->setItem(28, 6, __qtablewidgetitem239);
        QTableWidgetItem *__qtablewidgetitem240 = new QTableWidgetItem();
        tableWidget->setItem(28, 7, __qtablewidgetitem240);
        QTableWidgetItem *__qtablewidgetitem241 = new QTableWidgetItem();
        tableWidget->setItem(29, 1, __qtablewidgetitem241);
        QTableWidgetItem *__qtablewidgetitem242 = new QTableWidgetItem();
        tableWidget->setItem(29, 2, __qtablewidgetitem242);
        QTableWidgetItem *__qtablewidgetitem243 = new QTableWidgetItem();
        tableWidget->setItem(29, 3, __qtablewidgetitem243);
        QTableWidgetItem *__qtablewidgetitem244 = new QTableWidgetItem();
        tableWidget->setItem(29, 4, __qtablewidgetitem244);
        QTableWidgetItem *__qtablewidgetitem245 = new QTableWidgetItem();
        tableWidget->setItem(29, 5, __qtablewidgetitem245);
        QTableWidgetItem *__qtablewidgetitem246 = new QTableWidgetItem();
        tableWidget->setItem(29, 6, __qtablewidgetitem246);
        QTableWidgetItem *__qtablewidgetitem247 = new QTableWidgetItem();
        tableWidget->setItem(29, 7, __qtablewidgetitem247);
        tableWidget->setObjectName("tableWidget");
        tableWidget->setGeometry(QRect(40, 100, 801, 931));
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(670, 30, 51, 51));
        pushButton_2 = new QPushButton(centralwidget);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(730, 30, 51, 51));
        pushButton_3 = new QPushButton(centralwidget);
        pushButton_3->setObjectName("pushButton_3");
        pushButton_3->setGeometry(QRect(790, 30, 51, 51));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(520, 70, 141, 21));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(850, 50, 131, 21));
        dateEdit = new QDateEdit(centralwidget);
        dateEdit->setObjectName("dateEdit");
        dateEdit->setGeometry(QRect(250, 70, 110, 25));
        dateEdit_2 = new QDateEdit(centralwidget);
        dateEdit_2->setObjectName("dateEdit_2");
        dateEdit_2->setGeometry(QRect(400, 70, 110, 25));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(370, 70, 21, 21));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(428, 30, 91, 20));
        collectionTotal = new QLabel(centralwidget);
        collectionTotal->setObjectName("collectionTotal");
        collectionTotal->setGeometry(QRect(530, 20, 121, 41));
        QFont font;
        font.setPointSize(16);
        collectionTotal->setFont(font);
        CurrentlyDue->setCentralWidget(centralwidget);
        label_3->raise();
        label->raise();
        tableWidget->raise();
        pushButton->raise();
        pushButton_2->raise();
        pushButton_3->raise();
        label_2->raise();
        dateEdit->raise();
        dateEdit_2->raise();
        label_4->raise();
        label_5->raise();
        collectionTotal->raise();
        statusbar = new QStatusBar(CurrentlyDue);
        statusbar->setObjectName("statusbar");
        CurrentlyDue->setStatusBar(statusbar);

        retranslateUi(CurrentlyDue);

        QMetaObject::connectSlotsByName(CurrentlyDue);
    } // setupUi

    void retranslateUi(QMainWindow *CurrentlyDue)
    {
        CurrentlyDue->setWindowTitle(QCoreApplication::translate("CurrentlyDue", "MainWindow", nullptr));
        actionChange_Week->setText(QCoreApplication::translate("CurrentlyDue", "Change Week", nullptr));
        label->setText(QCoreApplication::translate("CurrentlyDue", "<html><head/><body><p><span style=\" font-size:20pt;\">Currently Due</span></p></body></html>", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("CurrentlyDue", "Paid?", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("CurrentlyDue", "Bal?", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("CurrentlyDue", "Name", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("CurrentlyDue", "Apartment", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("CurrentlyDue", "Rent", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("CurrentlyDue", "Balance", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("CurrentlyDue", "Paid Through", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->horizontalHeaderItem(7);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("CurrentlyDue", "Frequency", nullptr));

        const bool __sortingEnabled = tableWidget->isSortingEnabled();
        tableWidget->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget->item(0, 1);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget->item(0, 2);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("CurrentlyDue", "John Smith", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget->item(0, 3);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("CurrentlyDue", "123 Main St - 1F", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget->item(0, 4);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("CurrentlyDue", "$120.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget->item(0, 5);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget->item(0, 6);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget->item(0, 7);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget->item(1, 1);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget->item(1, 2);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("CurrentlyDue", "John Doe", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget->item(1, 3);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("CurrentlyDue", "123 Main St - 2R", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget->item(1, 4);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("CurrentlyDue", "$600.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget->item(1, 5);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget->item(1, 6);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget->item(1, 7);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget->item(2, 1);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget->item(2, 2);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("CurrentlyDue", "Jane Doe", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget->item(2, 3);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("CurrentlyDue", "123 Main St - 1R", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget->item(2, 4);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("CurrentlyDue", "$160.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget->item(2, 5);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget->item(2, 6);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget->item(2, 7);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget->item(3, 1);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget->item(3, 2);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("CurrentlyDue", "Jane Smith", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget->item(3, 3);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("CurrentlyDue", "123 Main St - 3FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget->item(3, 4);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("CurrentlyDue", "$125.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget->item(3, 5);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("CurrentlyDue", "$60.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget->item(3, 6);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget->item(3, 7);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget->item(4, 1);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget->item(4, 2);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("CurrentlyDue", "Walter White", nullptr));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget->item(4, 3);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("CurrentlyDue", "308 Negra Arroyo Ln - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget->item(4, 4);
        ___qtablewidgetitem39->setText(QCoreApplication::translate("CurrentlyDue", "$650.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget->item(4, 5);
        ___qtablewidgetitem40->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget->item(4, 6);
        ___qtablewidgetitem41->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget->item(4, 7);
        ___qtablewidgetitem42->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget->item(5, 1);
        ___qtablewidgetitem43->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget->item(5, 2);
        ___qtablewidgetitem44->setText(QCoreApplication::translate("CurrentlyDue", "Nacho Varga", nullptr));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget->item(5, 3);
        ___qtablewidgetitem45->setText(QCoreApplication::translate("CurrentlyDue", "432 Houston Rd - 2FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget->item(5, 4);
        ___qtablewidgetitem46->setText(QCoreApplication::translate("CurrentlyDue", "$190.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget->item(5, 5);
        ___qtablewidgetitem47->setText(QCoreApplication::translate("CurrentlyDue", "$100.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget->item(5, 6);
        ___qtablewidgetitem48->setText(QCoreApplication::translate("CurrentlyDue", "3/25/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget->item(5, 7);
        ___qtablewidgetitem49->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget->item(6, 1);
        ___qtablewidgetitem50->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget->item(6, 2);
        ___qtablewidgetitem51->setText(QCoreApplication::translate("CurrentlyDue", "Tuco Salamanca", nullptr));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget->item(6, 3);
        ___qtablewidgetitem52->setText(QCoreApplication::translate("CurrentlyDue", "7865 Somestreet St - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget->item(6, 4);
        ___qtablewidgetitem53->setText(QCoreApplication::translate("CurrentlyDue", "$120.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget->item(6, 5);
        ___qtablewidgetitem54->setText(QCoreApplication::translate("CurrentlyDue", "$80.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget->item(6, 6);
        ___qtablewidgetitem55->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget->item(6, 7);
        ___qtablewidgetitem56->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget->item(7, 1);
        ___qtablewidgetitem57->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget->item(7, 2);
        ___qtablewidgetitem58->setText(QCoreApplication::translate("CurrentlyDue", "Hector Salamanca", nullptr));
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget->item(7, 3);
        ___qtablewidgetitem59->setText(QCoreApplication::translate("CurrentlyDue", "37 Idontknow Rd - 1FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget->item(7, 4);
        ___qtablewidgetitem60->setText(QCoreApplication::translate("CurrentlyDue", "$120.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget->item(7, 5);
        ___qtablewidgetitem61->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget->item(7, 6);
        ___qtablewidgetitem62->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget->item(7, 7);
        ___qtablewidgetitem63->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget->item(8, 1);
        ___qtablewidgetitem64->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget->item(8, 2);
        ___qtablewidgetitem65->setText(QCoreApplication::translate("CurrentlyDue", "Kim Wexler", nullptr));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget->item(8, 3);
        ___qtablewidgetitem66->setText(QCoreApplication::translate("CurrentlyDue", "23 Ohio Ave - 1F", nullptr));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget->item(8, 4);
        ___qtablewidgetitem67->setText(QCoreApplication::translate("CurrentlyDue", "$120.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget->item(8, 5);
        ___qtablewidgetitem68->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget->item(8, 6);
        ___qtablewidgetitem69->setText(QCoreApplication::translate("CurrentlyDue", "3/25/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget->item(8, 7);
        ___qtablewidgetitem70->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget->item(9, 1);
        ___qtablewidgetitem71->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem72 = tableWidget->item(9, 2);
        ___qtablewidgetitem72->setText(QCoreApplication::translate("CurrentlyDue", "Jimmy McGill", nullptr));
        QTableWidgetItem *___qtablewidgetitem73 = tableWidget->item(9, 3);
        ___qtablewidgetitem73->setText(QCoreApplication::translate("CurrentlyDue", "24 Ohio Ave - 2R", nullptr));
        QTableWidgetItem *___qtablewidgetitem74 = tableWidget->item(9, 4);
        ___qtablewidgetitem74->setText(QCoreApplication::translate("CurrentlyDue", "$600.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem75 = tableWidget->item(9, 5);
        ___qtablewidgetitem75->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem76 = tableWidget->item(9, 6);
        ___qtablewidgetitem76->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem77 = tableWidget->item(9, 7);
        ___qtablewidgetitem77->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem78 = tableWidget->item(10, 1);
        ___qtablewidgetitem78->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem79 = tableWidget->item(10, 2);
        ___qtablewidgetitem79->setText(QCoreApplication::translate("CurrentlyDue", "Jesse Pinkman", nullptr));
        QTableWidgetItem *___qtablewidgetitem80 = tableWidget->item(10, 3);
        ___qtablewidgetitem80->setText(QCoreApplication::translate("CurrentlyDue", "25 Ohio Ave - 3FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem81 = tableWidget->item(10, 4);
        ___qtablewidgetitem81->setText(QCoreApplication::translate("CurrentlyDue", "$120.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem82 = tableWidget->item(10, 5);
        ___qtablewidgetitem82->setText(QCoreApplication::translate("CurrentlyDue", "$30.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem83 = tableWidget->item(10, 6);
        ___qtablewidgetitem83->setText(QCoreApplication::translate("CurrentlyDue", "3/18/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem84 = tableWidget->item(10, 7);
        ___qtablewidgetitem84->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem85 = tableWidget->item(11, 1);
        ___qtablewidgetitem85->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem86 = tableWidget->item(11, 2);
        ___qtablewidgetitem86->setText(QCoreApplication::translate("CurrentlyDue", "Gus Fring", nullptr));
        QTableWidgetItem *___qtablewidgetitem87 = tableWidget->item(11, 3);
        ___qtablewidgetitem87->setText(QCoreApplication::translate("CurrentlyDue", "87 Some Rd - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem88 = tableWidget->item(11, 4);
        ___qtablewidgetitem88->setText(QCoreApplication::translate("CurrentlyDue", "$600.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem89 = tableWidget->item(11, 5);
        ___qtablewidgetitem89->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem90 = tableWidget->item(11, 6);
        ___qtablewidgetitem90->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem91 = tableWidget->item(11, 7);
        ___qtablewidgetitem91->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem92 = tableWidget->item(12, 1);
        ___qtablewidgetitem92->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem93 = tableWidget->item(12, 2);
        ___qtablewidgetitem93->setText(QCoreApplication::translate("CurrentlyDue", "Hank Schrader", nullptr));
        QTableWidgetItem *___qtablewidgetitem94 = tableWidget->item(12, 3);
        ___qtablewidgetitem94->setText(QCoreApplication::translate("CurrentlyDue", "657 Vine St - 1FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem95 = tableWidget->item(12, 4);
        ___qtablewidgetitem95->setText(QCoreApplication::translate("CurrentlyDue", "$600.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem96 = tableWidget->item(12, 5);
        ___qtablewidgetitem96->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem97 = tableWidget->item(12, 6);
        ___qtablewidgetitem97->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem98 = tableWidget->item(12, 7);
        ___qtablewidgetitem98->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem99 = tableWidget->item(13, 1);
        ___qtablewidgetitem99->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem100 = tableWidget->item(13, 2);
        ___qtablewidgetitem100->setText(QCoreApplication::translate("CurrentlyDue", "Mike Ehrmantraut", nullptr));
        QTableWidgetItem *___qtablewidgetitem101 = tableWidget->item(13, 3);
        ___qtablewidgetitem101->setText(QCoreApplication::translate("CurrentlyDue", "789 Detour Ln - 3F", nullptr));
        QTableWidgetItem *___qtablewidgetitem102 = tableWidget->item(13, 4);
        ___qtablewidgetitem102->setText(QCoreApplication::translate("CurrentlyDue", "$280.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem103 = tableWidget->item(13, 5);
        ___qtablewidgetitem103->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem104 = tableWidget->item(13, 6);
        ___qtablewidgetitem104->setText(QCoreApplication::translate("CurrentlyDue", "3/18/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem105 = tableWidget->item(13, 7);
        ___qtablewidgetitem105->setText(QCoreApplication::translate("CurrentlyDue", "Biweekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem106 = tableWidget->item(14, 1);
        ___qtablewidgetitem106->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem107 = tableWidget->item(14, 2);
        ___qtablewidgetitem107->setText(QCoreApplication::translate("CurrentlyDue", "Nick Arlinghaus", nullptr));
        QTableWidgetItem *___qtablewidgetitem108 = tableWidget->item(14, 3);
        ___qtablewidgetitem108->setText(QCoreApplication::translate("CurrentlyDue", "8 W Hollister St - 3FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem109 = tableWidget->item(14, 4);
        ___qtablewidgetitem109->setText(QCoreApplication::translate("CurrentlyDue", "$120.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem110 = tableWidget->item(14, 5);
        ___qtablewidgetitem110->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem111 = tableWidget->item(14, 6);
        ___qtablewidgetitem111->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem112 = tableWidget->item(14, 7);
        ___qtablewidgetitem112->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem113 = tableWidget->item(15, 1);
        ___qtablewidgetitem113->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem114 = tableWidget->item(15, 2);
        ___qtablewidgetitem114->setText(QCoreApplication::translate("CurrentlyDue", "Sam Dotson", nullptr));
        QTableWidgetItem *___qtablewidgetitem115 = tableWidget->item(15, 3);
        ___qtablewidgetitem115->setText(QCoreApplication::translate("CurrentlyDue", "8 W Hollister St - 3FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem116 = tableWidget->item(15, 4);
        ___qtablewidgetitem116->setText(QCoreApplication::translate("CurrentlyDue", "$240.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem117 = tableWidget->item(15, 5);
        ___qtablewidgetitem117->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem118 = tableWidget->item(15, 6);
        ___qtablewidgetitem118->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem119 = tableWidget->item(15, 7);
        ___qtablewidgetitem119->setText(QCoreApplication::translate("CurrentlyDue", "Biweekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem120 = tableWidget->item(16, 1);
        ___qtablewidgetitem120->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem121 = tableWidget->item(16, 2);
        ___qtablewidgetitem121->setText(QCoreApplication::translate("CurrentlyDue", "Tim Arlinghaus", nullptr));
        QTableWidgetItem *___qtablewidgetitem122 = tableWidget->item(16, 3);
        ___qtablewidgetitem122->setText(QCoreApplication::translate("CurrentlyDue", "1111 Russel St - 2FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem123 = tableWidget->item(16, 4);
        ___qtablewidgetitem123->setText(QCoreApplication::translate("CurrentlyDue", "$165.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem124 = tableWidget->item(16, 5);
        ___qtablewidgetitem124->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem125 = tableWidget->item(16, 6);
        ___qtablewidgetitem125->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem126 = tableWidget->item(16, 7);
        ___qtablewidgetitem126->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem127 = tableWidget->item(17, 1);
        ___qtablewidgetitem127->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem128 = tableWidget->item(17, 2);
        ___qtablewidgetitem128->setText(QCoreApplication::translate("CurrentlyDue", "Claire Thecat", nullptr));
        QTableWidgetItem *___qtablewidgetitem129 = tableWidget->item(17, 3);
        ___qtablewidgetitem129->setText(QCoreApplication::translate("CurrentlyDue", "8 W Hollisrter St - 3FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem130 = tableWidget->item(17, 4);
        ___qtablewidgetitem130->setText(QCoreApplication::translate("CurrentlyDue", "$270.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem131 = tableWidget->item(17, 5);
        ___qtablewidgetitem131->setText(QCoreApplication::translate("CurrentlyDue", "-$20.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem132 = tableWidget->item(17, 6);
        ___qtablewidgetitem132->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem133 = tableWidget->item(17, 7);
        ___qtablewidgetitem133->setText(QCoreApplication::translate("CurrentlyDue", "Biweekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem134 = tableWidget->item(18, 1);
        ___qtablewidgetitem134->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem135 = tableWidget->item(18, 2);
        ___qtablewidgetitem135->setText(QCoreApplication::translate("CurrentlyDue", "Kodi Thedog", nullptr));
        QTableWidgetItem *___qtablewidgetitem136 = tableWidget->item(18, 3);
        ___qtablewidgetitem136->setText(QCoreApplication::translate("CurrentlyDue", "1111 Russel St - 1FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem137 = tableWidget->item(18, 4);
        ___qtablewidgetitem137->setText(QCoreApplication::translate("CurrentlyDue", "$240.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem138 = tableWidget->item(18, 5);
        ___qtablewidgetitem138->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem139 = tableWidget->item(18, 6);
        ___qtablewidgetitem139->setText(QCoreApplication::translate("CurrentlyDue", "3/25/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem140 = tableWidget->item(18, 7);
        ___qtablewidgetitem140->setText(QCoreApplication::translate("CurrentlyDue", "Biweekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem141 = tableWidget->item(19, 1);
        ___qtablewidgetitem141->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem142 = tableWidget->item(19, 2);
        ___qtablewidgetitem142->setText(QCoreApplication::translate("CurrentlyDue", "Bojack Horseman", nullptr));
        QTableWidgetItem *___qtablewidgetitem143 = tableWidget->item(19, 3);
        ___qtablewidgetitem143->setText(QCoreApplication::translate("CurrentlyDue", "1475 Luck Hoof Ave - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem144 = tableWidget->item(19, 4);
        ___qtablewidgetitem144->setText(QCoreApplication::translate("CurrentlyDue", "$900.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem145 = tableWidget->item(19, 5);
        ___qtablewidgetitem145->setText(QCoreApplication::translate("CurrentlyDue", "$-35.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem146 = tableWidget->item(19, 6);
        ___qtablewidgetitem146->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem147 = tableWidget->item(19, 7);
        ___qtablewidgetitem147->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem148 = tableWidget->item(20, 1);
        ___qtablewidgetitem148->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem149 = tableWidget->item(20, 2);
        ___qtablewidgetitem149->setText(QCoreApplication::translate("CurrentlyDue", "Eric Cartman", nullptr));
        QTableWidgetItem *___qtablewidgetitem150 = tableWidget->item(20, 3);
        ___qtablewidgetitem150->setText(QCoreApplication::translate("CurrentlyDue", "1 Hotdog St - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem151 = tableWidget->item(20, 4);
        ___qtablewidgetitem151->setText(QCoreApplication::translate("CurrentlyDue", "$700.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem152 = tableWidget->item(20, 5);
        ___qtablewidgetitem152->setText(QCoreApplication::translate("CurrentlyDue", "$60.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem153 = tableWidget->item(20, 6);
        ___qtablewidgetitem153->setText(QCoreApplication::translate("CurrentlyDue", "3/4/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem154 = tableWidget->item(20, 7);
        ___qtablewidgetitem154->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem155 = tableWidget->item(21, 1);
        ___qtablewidgetitem155->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem156 = tableWidget->item(21, 2);
        ___qtablewidgetitem156->setText(QCoreApplication::translate("CurrentlyDue", "Stan Marsh", nullptr));
        QTableWidgetItem *___qtablewidgetitem157 = tableWidget->item(21, 3);
        ___qtablewidgetitem157->setText(QCoreApplication::translate("CurrentlyDue", "452 North Park Rd - 1FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem158 = tableWidget->item(21, 4);
        ___qtablewidgetitem158->setText(QCoreApplication::translate("CurrentlyDue", "$300.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem159 = tableWidget->item(21, 5);
        ___qtablewidgetitem159->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem160 = tableWidget->item(21, 6);
        ___qtablewidgetitem160->setText(QCoreApplication::translate("CurrentlyDue", "3/18/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem161 = tableWidget->item(21, 7);
        ___qtablewidgetitem161->setText(QCoreApplication::translate("CurrentlyDue", "Biweekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem162 = tableWidget->item(22, 1);
        ___qtablewidgetitem162->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem163 = tableWidget->item(22, 2);
        ___qtablewidgetitem163->setText(QCoreApplication::translate("CurrentlyDue", "Kyle Broflovski", nullptr));
        QTableWidgetItem *___qtablewidgetitem164 = tableWidget->item(22, 3);
        ___qtablewidgetitem164->setText(QCoreApplication::translate("CurrentlyDue", "78 Jimmy St - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem165 = tableWidget->item(22, 4);
        ___qtablewidgetitem165->setText(QCoreApplication::translate("CurrentlyDue", "$120.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem166 = tableWidget->item(22, 5);
        ___qtablewidgetitem166->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem167 = tableWidget->item(22, 6);
        ___qtablewidgetitem167->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem168 = tableWidget->item(22, 7);
        ___qtablewidgetitem168->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem169 = tableWidget->item(23, 1);
        ___qtablewidgetitem169->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem170 = tableWidget->item(23, 2);
        ___qtablewidgetitem170->setText(QCoreApplication::translate("CurrentlyDue", "Kenny McCormick", nullptr));
        QTableWidgetItem *___qtablewidgetitem171 = tableWidget->item(23, 3);
        ___qtablewidgetitem171->setText(QCoreApplication::translate("CurrentlyDue", "34 Jimmy St - 1FL", nullptr));
        QTableWidgetItem *___qtablewidgetitem172 = tableWidget->item(23, 4);
        ___qtablewidgetitem172->setText(QCoreApplication::translate("CurrentlyDue", "$650.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem173 = tableWidget->item(23, 5);
        ___qtablewidgetitem173->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem174 = tableWidget->item(23, 6);
        ___qtablewidgetitem174->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem175 = tableWidget->item(23, 7);
        ___qtablewidgetitem175->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem176 = tableWidget->item(24, 1);
        ___qtablewidgetitem176->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem177 = tableWidget->item(24, 2);
        ___qtablewidgetitem177->setText(QCoreApplication::translate("CurrentlyDue", "Jimmy Neutron", nullptr));
        QTableWidgetItem *___qtablewidgetitem178 = tableWidget->item(24, 3);
        ___qtablewidgetitem178->setText(QCoreApplication::translate("CurrentlyDue", "356 Nerd St - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem179 = tableWidget->item(24, 4);
        ___qtablewidgetitem179->setText(QCoreApplication::translate("CurrentlyDue", "$180.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem180 = tableWidget->item(24, 5);
        ___qtablewidgetitem180->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem181 = tableWidget->item(24, 6);
        ___qtablewidgetitem181->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem182 = tableWidget->item(24, 7);
        ___qtablewidgetitem182->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem183 = tableWidget->item(25, 1);
        ___qtablewidgetitem183->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem184 = tableWidget->item(25, 2);
        ___qtablewidgetitem184->setText(QCoreApplication::translate("CurrentlyDue", "Neville Pinto", nullptr));
        QTableWidgetItem *___qtablewidgetitem185 = tableWidget->item(25, 3);
        ___qtablewidgetitem185->setText(QCoreApplication::translate("CurrentlyDue", "2600 Clifton Ave - 2R", nullptr));
        QTableWidgetItem *___qtablewidgetitem186 = tableWidget->item(25, 4);
        ___qtablewidgetitem186->setText(QCoreApplication::translate("CurrentlyDue", "$600.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem187 = tableWidget->item(25, 5);
        ___qtablewidgetitem187->setText(QCoreApplication::translate("CurrentlyDue", "$70.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem188 = tableWidget->item(25, 6);
        ___qtablewidgetitem188->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem189 = tableWidget->item(25, 7);
        ___qtablewidgetitem189->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem190 = tableWidget->item(26, 1);
        ___qtablewidgetitem190->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem191 = tableWidget->item(26, 2);
        ___qtablewidgetitem191->setText(QCoreApplication::translate("CurrentlyDue", "Linus Torvalds", nullptr));
        QTableWidgetItem *___qtablewidgetitem192 = tableWidget->item(26, 3);
        ___qtablewidgetitem192->setText(QCoreApplication::translate("CurrentlyDue", "8 Canada Ln - 1R", nullptr));
        QTableWidgetItem *___qtablewidgetitem193 = tableWidget->item(26, 4);
        ___qtablewidgetitem193->setText(QCoreApplication::translate("CurrentlyDue", "$140.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem194 = tableWidget->item(26, 5);
        ___qtablewidgetitem194->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem195 = tableWidget->item(26, 6);
        ___qtablewidgetitem195->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem196 = tableWidget->item(26, 7);
        ___qtablewidgetitem196->setText(QCoreApplication::translate("CurrentlyDue", "Weekly", nullptr));
        QTableWidgetItem *___qtablewidgetitem197 = tableWidget->item(27, 1);
        ___qtablewidgetitem197->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem198 = tableWidget->item(27, 2);
        ___qtablewidgetitem198->setText(QCoreApplication::translate("CurrentlyDue", "Muffin Man", nullptr));
        QTableWidgetItem *___qtablewidgetitem199 = tableWidget->item(27, 3);
        ___qtablewidgetitem199->setText(QCoreApplication::translate("CurrentlyDue", "1 Drury Ln - 1F", nullptr));
        QTableWidgetItem *___qtablewidgetitem200 = tableWidget->item(27, 4);
        ___qtablewidgetitem200->setText(QCoreApplication::translate("CurrentlyDue", "$560.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem201 = tableWidget->item(27, 5);
        ___qtablewidgetitem201->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem202 = tableWidget->item(27, 6);
        ___qtablewidgetitem202->setText(QCoreApplication::translate("CurrentlyDue", "3/4/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem203 = tableWidget->item(27, 7);
        ___qtablewidgetitem203->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem204 = tableWidget->item(28, 1);
        ___qtablewidgetitem204->setText(QCoreApplication::translate("CurrentlyDue", "Yes", nullptr));
        QTableWidgetItem *___qtablewidgetitem205 = tableWidget->item(28, 2);
        ___qtablewidgetitem205->setText(QCoreApplication::translate("CurrentlyDue", "Ron Swanson", nullptr));
        QTableWidgetItem *___qtablewidgetitem206 = tableWidget->item(28, 3);
        ___qtablewidgetitem206->setText(QCoreApplication::translate("CurrentlyDue", "78 Pawnee St - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem207 = tableWidget->item(28, 4);
        ___qtablewidgetitem207->setText(QCoreApplication::translate("CurrentlyDue", "$800.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem208 = tableWidget->item(28, 5);
        ___qtablewidgetitem208->setText(QCoreApplication::translate("CurrentlyDue", "$100.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem209 = tableWidget->item(28, 6);
        ___qtablewidgetitem209->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem210 = tableWidget->item(28, 7);
        ___qtablewidgetitem210->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        QTableWidgetItem *___qtablewidgetitem211 = tableWidget->item(29, 1);
        ___qtablewidgetitem211->setText(QCoreApplication::translate("CurrentlyDue", "No", nullptr));
        QTableWidgetItem *___qtablewidgetitem212 = tableWidget->item(29, 2);
        ___qtablewidgetitem212->setText(QCoreApplication::translate("CurrentlyDue", "Leslie Knope", nullptr));
        QTableWidgetItem *___qtablewidgetitem213 = tableWidget->item(29, 3);
        ___qtablewidgetitem213->setText(QCoreApplication::translate("CurrentlyDue", "24 Pawnee St - HSE", nullptr));
        QTableWidgetItem *___qtablewidgetitem214 = tableWidget->item(29, 4);
        ___qtablewidgetitem214->setText(QCoreApplication::translate("CurrentlyDue", "$800.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem215 = tableWidget->item(29, 5);
        ___qtablewidgetitem215->setText(QCoreApplication::translate("CurrentlyDue", "$0.00", nullptr));
        QTableWidgetItem *___qtablewidgetitem216 = tableWidget->item(29, 6);
        ___qtablewidgetitem216->setText(QCoreApplication::translate("CurrentlyDue", "4/1/23", nullptr));
        QTableWidgetItem *___qtablewidgetitem217 = tableWidget->item(29, 7);
        ___qtablewidgetitem217->setText(QCoreApplication::translate("CurrentlyDue", "Monthly", nullptr));
        tableWidget->setSortingEnabled(__sortingEnabled);

        pushButton->setText(QCoreApplication::translate("CurrentlyDue", "Undo", nullptr));
        pushButton_2->setText(QCoreApplication::translate("CurrentlyDue", "Save", nullptr));
        pushButton_3->setText(QCoreApplication::translate("CurrentlyDue", "Finish", nullptr));
        label_2->setText(QCoreApplication::translate("CurrentlyDue", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#aa0000;\">Unsaved Changes</span></p></body></html>", nullptr));
        label_3->setText(QCoreApplication::translate("CurrentlyDue", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#00aa00;\">Saved!</span></p></body></html>", nullptr));
        label_4->setText(QCoreApplication::translate("CurrentlyDue", "<html><head/><body><p align=\"center\">to</p></body></html>", nullptr));
        label_5->setText(QCoreApplication::translate("CurrentlyDue", "Collection Total:", nullptr));
        collectionTotal->setText(QCoreApplication::translate("CurrentlyDue", "$00,000.00", nullptr));
    } // retranslateUi

};

namespace Ui {
    class CurrentlyDue: public Ui_CurrentlyDue {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CURRENTLYDUE_H
