/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionDatabase;
    QAction *actionPrint;
    QAction *actionAbout;
    QAction *actionSteve_Mode;
    QWidget *centralwidget;
    QStackedWidget *mainWidgets;
    QWidget *mainmenu;
    QLabel *label_2;
    QGraphicsView *insightsview;
    QPushButton *tenantInfoButton;
    QPushButton *currentlyDueButton;
    QPushButton *buildingsButton;
    QPushButton *resourcesButton;
    QPushButton *reportsButton;
    QPushButton *exitButton;
    QPushButton *QpBalanceSheetButton;
    QPushButton *QpColListButton;
    QLabel *label;
    QLabel *label_5;
    QWidget *buildings;
    QStackedWidget *buildingsWidget;
    QWidget *mainBuildingsWidget;
    QGraphicsView *graphicsView_5;
    QPushButton *addBuildingButton;
    QPushButton *editBuildingsButton;
    QLabel *label_11;
    QWidget *addBuildingWidget;
    QPushButton *buildingsBackButton;
    QLabel *label_12;
    QLineEdit *addBuildingAddr;
    QLabel *label_13;
    QLineEdit *addBuildingCity;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_14;
    QSpinBox *addBuildingNumUnits;
    QLineEdit *addBuildingWater;
    QLabel *label_19;
    QLineEdit *addBuildingGas;
    QLabel *label_20;
    QPushButton *addBuildingsSaveButton;
    QComboBox *addBuildingState;
    QWidget *editBuildingsWidget;
    QLabel *label_22;
    QPushButton *buildingsBackButton_3;
    QLabel *label_23;
    QLabel *label_24;
    QLineEdit *editBuildingCity;
    QLabel *label_26;
    QLineEdit *editBuildingAddr;
    QSpinBox *editBuildingNumUnits;
    QLabel *label_27;
    QLineEdit *editBuildingWater;
    QLabel *label_28;
    QLabel *label_30;
    QLineEdit *editBuildingGas;
    QComboBox *editBuildingCombo;
    QLabel *label_32;
    QPushButton *editBuildingsSaveButton;
    QComboBox *editBuildingState;
    QLabel *label_10;
    QPushButton *mainMenuButton1;
    QWidget *reports;
    QLabel *label_3;
    QPushButton *mainMenuButton2;
    QStackedWidget *stackedWidget;
    QWidget *page_3;
    QGraphicsView *graphicsView_2;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_18;
    QPushButton *pushButton_14;
    QPushButton *pushButton_13;
    QPushButton *pushButton_16;
    QPushButton *pushButton_12;
    QPushButton *pushButton_17;
    QPushButton *pushButton_15;
    QLabel *label_4;
    QPushButton *pushButton_11;
    QWidget *page_4;
    QWidget *tenantInfo;
    QLabel *label_6;
    QPushButton *mainMenuButton3;
    QStackedWidget *tenantInfoWidget;
    QWidget *tenantInfoMainWidget;
    QPushButton *pushButton_21;
    QPushButton *newTenantButton;
    QLabel *label_7;
    QGraphicsView *graphicsView_3;
    QPushButton *pushButton_20;
    QPushButton *pushButton_22;
    QWidget *newTenantWidget;
    QLabel *label_33;
    QPushButton *tenantInfoBackButton1;
    QLabel *label_34;
    QLineEdit *newFirstName;
    QLabel *label_35;
    QLineEdit *newLastName;
    QLabel *label_36;
    QLineEdit *newPhone;
    QLabel *label_37;
    QLineEdit *newNokName;
    QLabel *label_38;
    QLineEdit *newNokRelation;
    QLabel *label_39;
    QLineEdit *newNokPhone;
    QLabel *label_40;
    QComboBox *newTenantBuildingCombo;
    QLabel *label_41;
    QLabel *label_42;
    QLineEdit *newEmployerPhone;
    QLabel *label_43;
    QLineEdit *newDeposit;
    QLabel *label_44;
    QLineEdit *newRent;
    QLabel *label_45;
    QLineEdit *newEmployer;
    QLabel *label_46;
    QDateEdit *moveInDate;
    QLabel *label_47;
    QComboBox *newDueDayCombo;
    QLabel *label_48;
    QPlainTextEdit *newNotes;
    QPushButton *tenantInfoAddSubmit;
    QLabel *label_49;
    QComboBox *newFreqCombo;
    QLineEdit *newApartmentNum;
    QWidget *resources;
    QLabel *label_8;
    QPushButton *mainMenuButton4;
    QStackedWidget *utilitiesWidget;
    QWidget *page_7;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QLabel *label_9;
    QPushButton *pushButton_27;
    QPushButton *addWaterButton;
    QPushButton *pushButton_26;
    QGraphicsView *graphicsView_4;
    QPushButton *pushButton_29;
    QWidget *addWater;
    QLineEdit *addBuildingCity_2;
    QDateEdit *dateEdit;
    QComboBox *comboBox;
    QPushButton *tenantInfoBackButton1_2;
    QPushButton *tenantInfoAddSubmit_2;
    QLabel *label_25;
    QLabel *label_21;
    QLabel *label_18;
    QLabel *label_17;
    QMenuBar *menubar;
    QMenu *menumainwindow;
    QMenu *menuHelp;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(807, 581);
        actionDatabase = new QAction(MainWindow);
        actionDatabase->setObjectName("actionDatabase");
        actionPrint = new QAction(MainWindow);
        actionPrint->setObjectName("actionPrint");
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName("actionAbout");
        actionSteve_Mode = new QAction(MainWindow);
        actionSteve_Mode->setObjectName("actionSteve_Mode");
        actionSteve_Mode->setCheckable(true);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        mainWidgets = new QStackedWidget(centralwidget);
        mainWidgets->setObjectName("mainWidgets");
        mainWidgets->setGeometry(QRect(0, 0, 801, 541));
        mainmenu = new QWidget();
        mainmenu->setObjectName("mainmenu");
        label_2 = new QLabel(mainmenu);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(40, 0, 171, 91));
        insightsview = new QGraphicsView(mainmenu);
        insightsview->setObjectName("insightsview");
        insightsview->setGeometry(QRect(40, 90, 391, 431));
        tenantInfoButton = new QPushButton(mainmenu);
        tenantInfoButton->setObjectName("tenantInfoButton");
        tenantInfoButton->setGeometry(QRect(460, 90, 141, 81));
        QFont font;
        font.setPointSize(15);
        tenantInfoButton->setFont(font);
        currentlyDueButton = new QPushButton(mainmenu);
        currentlyDueButton->setObjectName("currentlyDueButton");
        currentlyDueButton->setGeometry(QRect(620, 90, 141, 81));
        currentlyDueButton->setFont(font);
        buildingsButton = new QPushButton(mainmenu);
        buildingsButton->setObjectName("buildingsButton");
        buildingsButton->setGeometry(QRect(460, 200, 141, 81));
        buildingsButton->setFont(font);
        resourcesButton = new QPushButton(mainmenu);
        resourcesButton->setObjectName("resourcesButton");
        resourcesButton->setGeometry(QRect(620, 200, 141, 81));
        resourcesButton->setFont(font);
        reportsButton = new QPushButton(mainmenu);
        reportsButton->setObjectName("reportsButton");
        reportsButton->setGeometry(QRect(460, 310, 141, 81));
        reportsButton->setFont(font);
        exitButton = new QPushButton(mainmenu);
        exitButton->setObjectName("exitButton");
        exitButton->setGeometry(QRect(620, 310, 141, 81));
        exitButton->setFont(font);
        QpBalanceSheetButton = new QPushButton(mainmenu);
        QpBalanceSheetButton->setObjectName("QpBalanceSheetButton");
        QpBalanceSheetButton->setGeometry(QRect(460, 470, 141, 51));
        QFont font1;
        font1.setPointSize(11);
        QpBalanceSheetButton->setFont(font1);
        QpColListButton = new QPushButton(mainmenu);
        QpColListButton->setObjectName("QpColListButton");
        QpColListButton->setGeometry(QRect(620, 470, 141, 51));
        QpColListButton->setFont(font1);
        label = new QLabel(mainmenu);
        label->setObjectName("label");
        label->setGeometry(QRect(540, 430, 141, 31));
        label_5 = new QLabel(mainmenu);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(200, 270, 49, 16));
        mainWidgets->addWidget(mainmenu);
        buildings = new QWidget();
        buildings->setObjectName("buildings");
        buildingsWidget = new QStackedWidget(buildings);
        buildingsWidget->setObjectName("buildingsWidget");
        buildingsWidget->setGeometry(QRect(0, 10, 801, 551));
        mainBuildingsWidget = new QWidget();
        mainBuildingsWidget->setObjectName("mainBuildingsWidget");
        graphicsView_5 = new QGraphicsView(mainBuildingsWidget);
        graphicsView_5->setObjectName("graphicsView_5");
        graphicsView_5->setGeometry(QRect(40, 80, 391, 431));
        addBuildingButton = new QPushButton(mainBuildingsWidget);
        addBuildingButton->setObjectName("addBuildingButton");
        addBuildingButton->setGeometry(QRect(460, 240, 141, 81));
        addBuildingButton->setFont(font);
        editBuildingsButton = new QPushButton(mainBuildingsWidget);
        editBuildingsButton->setObjectName("editBuildingsButton");
        editBuildingsButton->setGeometry(QRect(620, 240, 141, 81));
        editBuildingsButton->setFont(font);
        label_11 = new QLabel(mainBuildingsWidget);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(160, 270, 81, 16));
        buildingsWidget->addWidget(mainBuildingsWidget);
        addBuildingWidget = new QWidget();
        addBuildingWidget->setObjectName("addBuildingWidget");
        buildingsBackButton = new QPushButton(addBuildingWidget);
        buildingsBackButton->setObjectName("buildingsBackButton");
        buildingsBackButton->setGeometry(QRect(640, 10, 51, 51));
        label_12 = new QLabel(addBuildingWidget);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(40, 65, 101, 21));
        addBuildingAddr = new QLineEdit(addBuildingWidget);
        addBuildingAddr->setObjectName("addBuildingAddr");
        addBuildingAddr->setGeometry(QRect(140, 140, 131, 41));
        label_13 = new QLabel(addBuildingWidget);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(40, 150, 91, 16));
        addBuildingCity = new QLineEdit(addBuildingWidget);
        addBuildingCity->setObjectName("addBuildingCity");
        addBuildingCity->setGeometry(QRect(140, 210, 131, 41));
        label_15 = new QLabel(addBuildingWidget);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(40, 220, 91, 16));
        label_16 = new QLabel(addBuildingWidget);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(40, 290, 91, 16));
        label_14 = new QLabel(addBuildingWidget);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(360, 145, 101, 31));
        addBuildingNumUnits = new QSpinBox(addBuildingWidget);
        addBuildingNumUnits->setObjectName("addBuildingNumUnits");
        addBuildingNumUnits->setGeometry(QRect(550, 140, 51, 41));
        addBuildingWater = new QLineEdit(addBuildingWidget);
        addBuildingWater->setObjectName("addBuildingWater");
        addBuildingWater->setGeometry(QRect(550, 210, 131, 41));
        label_19 = new QLabel(addBuildingWidget);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(360, 210, 161, 41));
        addBuildingGas = new QLineEdit(addBuildingWidget);
        addBuildingGas->setObjectName("addBuildingGas");
        addBuildingGas->setGeometry(QRect(550, 280, 131, 41));
        label_20 = new QLabel(addBuildingWidget);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(360, 280, 151, 41));
        addBuildingsSaveButton = new QPushButton(addBuildingWidget);
        addBuildingsSaveButton->setObjectName("addBuildingsSaveButton");
        addBuildingsSaveButton->setGeometry(QRect(570, 10, 51, 51));
        addBuildingState = new QComboBox(addBuildingWidget);
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->addItem(QString());
        addBuildingState->setObjectName("addBuildingState");
        addBuildingState->setGeometry(QRect(140, 280, 131, 41));
        buildingsWidget->addWidget(addBuildingWidget);
        editBuildingsWidget = new QWidget();
        editBuildingsWidget->setObjectName("editBuildingsWidget");
        label_22 = new QLabel(editBuildingsWidget);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(40, 60, 101, 31));
        buildingsBackButton_3 = new QPushButton(editBuildingsWidget);
        buildingsBackButton_3->setObjectName("buildingsBackButton_3");
        buildingsBackButton_3->setGeometry(QRect(640, 10, 51, 51));
        label_23 = new QLabel(editBuildingsWidget);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(360, 280, 161, 41));
        label_24 = new QLabel(editBuildingsWidget);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(360, 210, 161, 41));
        editBuildingCity = new QLineEdit(editBuildingsWidget);
        editBuildingCity->setObjectName("editBuildingCity");
        editBuildingCity->setGeometry(QRect(140, 210, 131, 41));
        label_26 = new QLabel(editBuildingsWidget);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(360, 145, 101, 31));
        editBuildingAddr = new QLineEdit(editBuildingsWidget);
        editBuildingAddr->setObjectName("editBuildingAddr");
        editBuildingAddr->setGeometry(QRect(140, 140, 131, 41));
        editBuildingNumUnits = new QSpinBox(editBuildingsWidget);
        editBuildingNumUnits->setObjectName("editBuildingNumUnits");
        editBuildingNumUnits->setGeometry(QRect(550, 140, 51, 41));
        label_27 = new QLabel(editBuildingsWidget);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(40, 290, 91, 16));
        editBuildingWater = new QLineEdit(editBuildingsWidget);
        editBuildingWater->setObjectName("editBuildingWater");
        editBuildingWater->setGeometry(QRect(550, 210, 131, 41));
        label_28 = new QLabel(editBuildingsWidget);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(40, 150, 91, 16));
        label_30 = new QLabel(editBuildingsWidget);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(40, 220, 91, 16));
        editBuildingGas = new QLineEdit(editBuildingsWidget);
        editBuildingGas->setObjectName("editBuildingGas");
        editBuildingGas->setGeometry(QRect(550, 280, 131, 41));
        editBuildingCombo = new QComboBox(editBuildingsWidget);
        editBuildingCombo->setObjectName("editBuildingCombo");
        editBuildingCombo->setGeometry(QRect(380, 80, 171, 31));
        label_32 = new QLabel(editBuildingsWidget);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(250, 80, 101, 31));
        editBuildingsSaveButton = new QPushButton(editBuildingsWidget);
        editBuildingsSaveButton->setObjectName("editBuildingsSaveButton");
        editBuildingsSaveButton->setGeometry(QRect(570, 10, 51, 51));
        editBuildingState = new QComboBox(editBuildingsWidget);
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->addItem(QString());
        editBuildingState->setObjectName("editBuildingState");
        editBuildingState->setGeometry(QRect(140, 280, 131, 41));
        buildingsWidget->addWidget(editBuildingsWidget);
        label_10 = new QLabel(buildings);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(40, 0, 171, 91));
        mainMenuButton1 = new QPushButton(buildings);
        mainMenuButton1->setObjectName("mainMenuButton1");
        mainMenuButton1->setGeometry(QRect(710, 20, 51, 51));
        mainWidgets->addWidget(buildings);
        reports = new QWidget();
        reports->setObjectName("reports");
        label_3 = new QLabel(reports);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(40, 0, 171, 91));
        mainMenuButton2 = new QPushButton(reports);
        mainMenuButton2->setObjectName("mainMenuButton2");
        mainMenuButton2->setGeometry(QRect(710, 20, 51, 51));
        stackedWidget = new QStackedWidget(reports);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 10, 801, 551));
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        graphicsView_2 = new QGraphicsView(page_3);
        graphicsView_2->setObjectName("graphicsView_2");
        graphicsView_2->setGeometry(QRect(40, 80, 391, 431));
        pushButton_9 = new QPushButton(page_3);
        pushButton_9->setObjectName("pushButton_9");
        pushButton_9->setGeometry(QRect(460, 80, 141, 71));
        pushButton_9->setFont(font);
        pushButton_10 = new QPushButton(page_3);
        pushButton_10->setObjectName("pushButton_10");
        pushButton_10->setGeometry(QRect(460, 170, 141, 71));
        pushButton_10->setFont(font);
        pushButton_18 = new QPushButton(page_3);
        pushButton_18->setObjectName("pushButton_18");
        pushButton_18->setGeometry(QRect(620, 80, 141, 71));
        pushButton_18->setFont(font);
        pushButton_14 = new QPushButton(page_3);
        pushButton_14->setObjectName("pushButton_14");
        pushButton_14->setGeometry(QRect(620, 170, 141, 71));
        pushButton_14->setFont(font);
        pushButton_13 = new QPushButton(page_3);
        pushButton_13->setObjectName("pushButton_13");
        pushButton_13->setGeometry(QRect(460, 440, 141, 71));
        pushButton_13->setFont(font);
        pushButton_16 = new QPushButton(page_3);
        pushButton_16->setObjectName("pushButton_16");
        pushButton_16->setGeometry(QRect(620, 440, 141, 71));
        pushButton_16->setFont(font);
        pushButton_12 = new QPushButton(page_3);
        pushButton_12->setObjectName("pushButton_12");
        pushButton_12->setGeometry(QRect(460, 350, 141, 71));
        pushButton_12->setFont(font);
        pushButton_17 = new QPushButton(page_3);
        pushButton_17->setObjectName("pushButton_17");
        pushButton_17->setGeometry(QRect(620, 350, 141, 71));
        pushButton_17->setFont(font);
        pushButton_15 = new QPushButton(page_3);
        pushButton_15->setObjectName("pushButton_15");
        pushButton_15->setGeometry(QRect(620, 260, 141, 71));
        pushButton_15->setFont(font);
        label_4 = new QLabel(page_3);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(120, 260, 181, 16));
        pushButton_11 = new QPushButton(page_3);
        pushButton_11->setObjectName("pushButton_11");
        pushButton_11->setGeometry(QRect(460, 260, 141, 71));
        pushButton_11->setFont(font);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        stackedWidget->addWidget(page_4);
        mainWidgets->addWidget(reports);
        stackedWidget->raise();
        label_3->raise();
        mainMenuButton2->raise();
        tenantInfo = new QWidget();
        tenantInfo->setObjectName("tenantInfo");
        label_6 = new QLabel(tenantInfo);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(40, 0, 171, 91));
        mainMenuButton3 = new QPushButton(tenantInfo);
        mainMenuButton3->setObjectName("mainMenuButton3");
        mainMenuButton3->setGeometry(QRect(710, 20, 51, 51));
        tenantInfoWidget = new QStackedWidget(tenantInfo);
        tenantInfoWidget->setObjectName("tenantInfoWidget");
        tenantInfoWidget->setGeometry(QRect(0, 10, 801, 551));
        tenantInfoMainWidget = new QWidget();
        tenantInfoMainWidget->setObjectName("tenantInfoMainWidget");
        pushButton_21 = new QPushButton(tenantInfoMainWidget);
        pushButton_21->setObjectName("pushButton_21");
        pushButton_21->setGeometry(QRect(460, 190, 301, 81));
        pushButton_21->setFont(font);
        newTenantButton = new QPushButton(tenantInfoMainWidget);
        newTenantButton->setObjectName("newTenantButton");
        newTenantButton->setGeometry(QRect(460, 430, 301, 81));
        newTenantButton->setFont(font);
        label_7 = new QLabel(tenantInfoMainWidget);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(200, 260, 71, 16));
        graphicsView_3 = new QGraphicsView(tenantInfoMainWidget);
        graphicsView_3->setObjectName("graphicsView_3");
        graphicsView_3->setGeometry(QRect(40, 80, 391, 431));
        pushButton_20 = new QPushButton(tenantInfoMainWidget);
        pushButton_20->setObjectName("pushButton_20");
        pushButton_20->setGeometry(QRect(460, 80, 301, 81));
        pushButton_20->setFont(font);
        pushButton_22 = new QPushButton(tenantInfoMainWidget);
        pushButton_22->setObjectName("pushButton_22");
        pushButton_22->setGeometry(QRect(460, 300, 301, 81));
        pushButton_22->setFont(font);
        tenantInfoWidget->addWidget(tenantInfoMainWidget);
        graphicsView_3->raise();
        pushButton_21->raise();
        newTenantButton->raise();
        label_7->raise();
        pushButton_20->raise();
        pushButton_22->raise();
        newTenantWidget = new QWidget();
        newTenantWidget->setObjectName("newTenantWidget");
        label_33 = new QLabel(newTenantWidget);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(40, 60, 101, 31));
        tenantInfoBackButton1 = new QPushButton(newTenantWidget);
        tenantInfoBackButton1->setObjectName("tenantInfoBackButton1");
        tenantInfoBackButton1->setGeometry(QRect(640, 10, 51, 51));
        label_34 = new QLabel(newTenantWidget);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(40, 130, 101, 41));
        newFirstName = new QLineEdit(newTenantWidget);
        newFirstName->setObjectName("newFirstName");
        newFirstName->setGeometry(QRect(150, 130, 121, 41));
        label_35 = new QLabel(newTenantWidget);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(40, 190, 101, 41));
        newLastName = new QLineEdit(newTenantWidget);
        newLastName->setObjectName("newLastName");
        newLastName->setGeometry(QRect(150, 190, 121, 41));
        label_36 = new QLabel(newTenantWidget);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(40, 250, 101, 41));
        newPhone = new QLineEdit(newTenantWidget);
        newPhone->setObjectName("newPhone");
        newPhone->setGeometry(QRect(150, 250, 121, 41));
        label_37 = new QLabel(newTenantWidget);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(40, 310, 101, 41));
        newNokName = new QLineEdit(newTenantWidget);
        newNokName->setObjectName("newNokName");
        newNokName->setGeometry(QRect(150, 310, 121, 41));
        label_38 = new QLabel(newTenantWidget);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(40, 370, 101, 41));
        newNokRelation = new QLineEdit(newTenantWidget);
        newNokRelation->setObjectName("newNokRelation");
        newNokRelation->setGeometry(QRect(150, 370, 121, 41));
        label_39 = new QLabel(newTenantWidget);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(40, 430, 101, 41));
        newNokPhone = new QLineEdit(newTenantWidget);
        newNokPhone->setObjectName("newNokPhone");
        newNokPhone->setGeometry(QRect(150, 430, 121, 41));
        label_40 = new QLabel(newTenantWidget);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(300, 130, 101, 41));
        newTenantBuildingCombo = new QComboBox(newTenantWidget);
        newTenantBuildingCombo->setObjectName("newTenantBuildingCombo");
        newTenantBuildingCombo->setGeometry(QRect(410, 130, 131, 41));
        label_41 = new QLabel(newTenantWidget);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(300, 190, 101, 41));
        label_42 = new QLabel(newTenantWidget);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(300, 250, 101, 41));
        newEmployerPhone = new QLineEdit(newTenantWidget);
        newEmployerPhone->setObjectName("newEmployerPhone");
        newEmployerPhone->setGeometry(QRect(410, 310, 131, 41));
        label_43 = new QLabel(newTenantWidget);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(300, 310, 101, 41));
        newDeposit = new QLineEdit(newTenantWidget);
        newDeposit->setObjectName("newDeposit");
        newDeposit->setGeometry(QRect(410, 370, 131, 41));
        label_44 = new QLabel(newTenantWidget);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(300, 370, 101, 41));
        newRent = new QLineEdit(newTenantWidget);
        newRent->setObjectName("newRent");
        newRent->setGeometry(QRect(410, 430, 131, 41));
        label_45 = new QLabel(newTenantWidget);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(300, 430, 101, 41));
        newEmployer = new QLineEdit(newTenantWidget);
        newEmployer->setObjectName("newEmployer");
        newEmployer->setGeometry(QRect(410, 250, 131, 41));
        label_46 = new QLabel(newTenantWidget);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(570, 130, 91, 41));
        moveInDate = new QDateEdit(newTenantWidget);
        moveInDate->setObjectName("moveInDate");
        moveInDate->setGeometry(QRect(670, 130, 91, 41));
        label_47 = new QLabel(newTenantWidget);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(570, 190, 91, 41));
        newDueDayCombo = new QComboBox(newTenantWidget);
        newDueDayCombo->addItem(QString());
        newDueDayCombo->addItem(QString());
        newDueDayCombo->addItem(QString());
        newDueDayCombo->addItem(QString());
        newDueDayCombo->addItem(QString());
        newDueDayCombo->addItem(QString());
        newDueDayCombo->addItem(QString());
        newDueDayCombo->addItem(QString());
        newDueDayCombo->setObjectName("newDueDayCombo");
        newDueDayCombo->setGeometry(QRect(670, 190, 91, 41));
        label_48 = new QLabel(newTenantWidget);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(570, 310, 91, 41));
        newNotes = new QPlainTextEdit(newTenantWidget);
        newNotes->setObjectName("newNotes");
        newNotes->setGeometry(QRect(570, 350, 191, 121));
        tenantInfoAddSubmit = new QPushButton(newTenantWidget);
        tenantInfoAddSubmit->setObjectName("tenantInfoAddSubmit");
        tenantInfoAddSubmit->setGeometry(QRect(570, 10, 51, 51));
        label_49 = new QLabel(newTenantWidget);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(570, 250, 91, 41));
        newFreqCombo = new QComboBox(newTenantWidget);
        newFreqCombo->addItem(QString());
        newFreqCombo->addItem(QString());
        newFreqCombo->addItem(QString());
        newFreqCombo->setObjectName("newFreqCombo");
        newFreqCombo->setGeometry(QRect(670, 250, 91, 41));
        newApartmentNum = new QLineEdit(newTenantWidget);
        newApartmentNum->setObjectName("newApartmentNum");
        newApartmentNum->setGeometry(QRect(410, 190, 131, 41));
        tenantInfoWidget->addWidget(newTenantWidget);
        mainWidgets->addWidget(tenantInfo);
        tenantInfoWidget->raise();
        label_6->raise();
        mainMenuButton3->raise();
        resources = new QWidget();
        resources->setObjectName("resources");
        label_8 = new QLabel(resources);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(40, 0, 171, 91));
        mainMenuButton4 = new QPushButton(resources);
        mainMenuButton4->setObjectName("mainMenuButton4");
        mainMenuButton4->setGeometry(QRect(710, 20, 51, 51));
        utilitiesWidget = new QStackedWidget(resources);
        utilitiesWidget->setObjectName("utilitiesWidget");
        utilitiesWidget->setGeometry(QRect(0, 10, 801, 551));
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        pushButton_30 = new QPushButton(page_7);
        pushButton_30->setObjectName("pushButton_30");
        pushButton_30->setGeometry(QRect(620, 300, 141, 81));
        pushButton_30->setFont(font);
        pushButton_31 = new QPushButton(page_7);
        pushButton_31->setObjectName("pushButton_31");
        pushButton_31->setGeometry(QRect(460, 300, 141, 81));
        pushButton_31->setFont(font);
        label_9 = new QLabel(page_7);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(140, 260, 191, 16));
        pushButton_27 = new QPushButton(page_7);
        pushButton_27->setObjectName("pushButton_27");
        pushButton_27->setGeometry(QRect(460, 190, 141, 81));
        pushButton_27->setFont(font);
        addWaterButton = new QPushButton(page_7);
        addWaterButton->setObjectName("addWaterButton");
        addWaterButton->setGeometry(QRect(620, 80, 141, 81));
        addWaterButton->setFont(font);
        pushButton_26 = new QPushButton(page_7);
        pushButton_26->setObjectName("pushButton_26");
        pushButton_26->setGeometry(QRect(460, 80, 141, 81));
        pushButton_26->setFont(font);
        graphicsView_4 = new QGraphicsView(page_7);
        graphicsView_4->setObjectName("graphicsView_4");
        graphicsView_4->setGeometry(QRect(40, 80, 391, 431));
        pushButton_29 = new QPushButton(page_7);
        pushButton_29->setObjectName("pushButton_29");
        pushButton_29->setGeometry(QRect(620, 190, 141, 81));
        pushButton_29->setFont(font);
        utilitiesWidget->addWidget(page_7);
        graphicsView_4->raise();
        pushButton_30->raise();
        pushButton_31->raise();
        pushButton_27->raise();
        addWaterButton->raise();
        pushButton_26->raise();
        pushButton_29->raise();
        label_9->raise();
        addWater = new QWidget();
        addWater->setObjectName("addWater");
        addBuildingCity_2 = new QLineEdit(addWater);
        addBuildingCity_2->setObjectName("addBuildingCity_2");
        addBuildingCity_2->setGeometry(QRect(140, 280, 131, 41));
        dateEdit = new QDateEdit(addWater);
        dateEdit->setObjectName("dateEdit");
        dateEdit->setGeometry(QRect(140, 210, 131, 41));
        comboBox = new QComboBox(addWater);
        comboBox->setObjectName("comboBox");
        comboBox->setGeometry(QRect(140, 140, 131, 41));
        tenantInfoBackButton1_2 = new QPushButton(addWater);
        tenantInfoBackButton1_2->setObjectName("tenantInfoBackButton1_2");
        tenantInfoBackButton1_2->setGeometry(QRect(640, 10, 51, 51));
        tenantInfoAddSubmit_2 = new QPushButton(addWater);
        tenantInfoAddSubmit_2->setObjectName("tenantInfoAddSubmit_2");
        tenantInfoAddSubmit_2->setGeometry(QRect(570, 10, 51, 51));
        label_25 = new QLabel(addWater);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(40, 65, 111, 21));
        label_21 = new QLabel(addWater);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(40, 290, 91, 21));
        label_18 = new QLabel(addWater);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(40, 150, 91, 21));
        label_17 = new QLabel(addWater);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(40, 220, 91, 16));
        utilitiesWidget->addWidget(addWater);
        mainWidgets->addWidget(resources);
        utilitiesWidget->raise();
        label_8->raise();
        mainMenuButton4->raise();
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 807, 21));
        menumainwindow = new QMenu(menubar);
        menumainwindow->setObjectName("menumainwindow");
        menuHelp = new QMenu(menubar);
        menuHelp->setObjectName("menuHelp");
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menumainwindow->menuAction());
        menubar->addAction(menuHelp->menuAction());
        menumainwindow->addSeparator();
        menumainwindow->addAction(actionDatabase);
        menumainwindow->addAction(actionPrint);
        menumainwindow->addSeparator();
        menumainwindow->addAction(actionSteve_Mode);
        menuHelp->addAction(actionAbout);

        retranslateUi(MainWindow);

        mainWidgets->setCurrentIndex(4);
        buildingsWidget->setCurrentIndex(1);
        stackedWidget->setCurrentIndex(0);
        tenantInfoWidget->setCurrentIndex(1);
        utilitiesWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        actionDatabase->setText(QCoreApplication::translate("MainWindow", "Database", nullptr));
        actionPrint->setText(QCoreApplication::translate("MainWindow", "Printer", nullptr));
        actionAbout->setText(QCoreApplication::translate("MainWindow", "About", nullptr));
        actionSteve_Mode->setText(QCoreApplication::translate("MainWindow", "Steve Mode", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Main Menu</span></p></body></html>", nullptr));
        tenantInfoButton->setText(QCoreApplication::translate("MainWindow", "Tenants", nullptr));
        currentlyDueButton->setText(QCoreApplication::translate("MainWindow", "Currently Due", nullptr));
        buildingsButton->setText(QCoreApplication::translate("MainWindow", "Buildings", nullptr));
        resourcesButton->setText(QCoreApplication::translate("MainWindow", "Utilities", nullptr));
        reportsButton->setText(QCoreApplication::translate("MainWindow", "Reports", nullptr));
        exitButton->setText(QCoreApplication::translate("MainWindow", "Exit", nullptr));
        QpBalanceSheetButton->setText(QCoreApplication::translate("MainWindow", "Balance Sheet", nullptr));
        QpColListButton->setText(QCoreApplication::translate("MainWindow", "Collection List \n"
"and Receipts", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Quick Print</span></p></body></html>", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Insights", nullptr));
        addBuildingButton->setText(QCoreApplication::translate("MainWindow", "Add Building", nullptr));
        editBuildingsButton->setText(QCoreApplication::translate("MainWindow", "Edit Buildings", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Buildings table", nullptr));
        buildingsBackButton->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Add Building</span></p></body></html>", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Street Address</span></p></body></html>", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">City</span></p></body></html>", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">State</span></p></body></html>", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of Units</span></p></body></html>", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Initial Water Meter Reading</span></p></body></html>", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Initial Gas Meter Reading</span></p></body></html>", nullptr));
        addBuildingsSaveButton->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        addBuildingState->setItemText(0, QCoreApplication::translate("MainWindow", "AL", nullptr));
        addBuildingState->setItemText(1, QCoreApplication::translate("MainWindow", "AK", nullptr));
        addBuildingState->setItemText(2, QCoreApplication::translate("MainWindow", "AZ", nullptr));
        addBuildingState->setItemText(3, QCoreApplication::translate("MainWindow", "AR", nullptr));
        addBuildingState->setItemText(4, QCoreApplication::translate("MainWindow", "CA", nullptr));
        addBuildingState->setItemText(5, QCoreApplication::translate("MainWindow", "CO", nullptr));
        addBuildingState->setItemText(6, QCoreApplication::translate("MainWindow", "CT", nullptr));
        addBuildingState->setItemText(7, QCoreApplication::translate("MainWindow", "DE", nullptr));
        addBuildingState->setItemText(8, QCoreApplication::translate("MainWindow", "DC", nullptr));
        addBuildingState->setItemText(9, QCoreApplication::translate("MainWindow", "FL", nullptr));
        addBuildingState->setItemText(10, QCoreApplication::translate("MainWindow", "GA", nullptr));
        addBuildingState->setItemText(11, QCoreApplication::translate("MainWindow", "HI", nullptr));
        addBuildingState->setItemText(12, QCoreApplication::translate("MainWindow", "ID", nullptr));
        addBuildingState->setItemText(13, QCoreApplication::translate("MainWindow", "IL", nullptr));
        addBuildingState->setItemText(14, QCoreApplication::translate("MainWindow", "IN", nullptr));
        addBuildingState->setItemText(15, QCoreApplication::translate("MainWindow", "IA", nullptr));
        addBuildingState->setItemText(16, QCoreApplication::translate("MainWindow", "KS", nullptr));
        addBuildingState->setItemText(17, QCoreApplication::translate("MainWindow", "KY", nullptr));
        addBuildingState->setItemText(18, QCoreApplication::translate("MainWindow", "LA", nullptr));
        addBuildingState->setItemText(19, QCoreApplication::translate("MainWindow", "ME", nullptr));
        addBuildingState->setItemText(20, QCoreApplication::translate("MainWindow", "MD", nullptr));
        addBuildingState->setItemText(21, QCoreApplication::translate("MainWindow", "MA", nullptr));
        addBuildingState->setItemText(22, QCoreApplication::translate("MainWindow", "MI", nullptr));
        addBuildingState->setItemText(23, QCoreApplication::translate("MainWindow", "MN", nullptr));
        addBuildingState->setItemText(24, QCoreApplication::translate("MainWindow", "MS", nullptr));
        addBuildingState->setItemText(25, QCoreApplication::translate("MainWindow", "MO", nullptr));
        addBuildingState->setItemText(26, QCoreApplication::translate("MainWindow", "MT", nullptr));
        addBuildingState->setItemText(27, QCoreApplication::translate("MainWindow", "NE", nullptr));
        addBuildingState->setItemText(28, QCoreApplication::translate("MainWindow", "NV", nullptr));
        addBuildingState->setItemText(29, QCoreApplication::translate("MainWindow", "NH", nullptr));
        addBuildingState->setItemText(30, QCoreApplication::translate("MainWindow", "NJ", nullptr));
        addBuildingState->setItemText(31, QCoreApplication::translate("MainWindow", "NM", nullptr));
        addBuildingState->setItemText(32, QCoreApplication::translate("MainWindow", "NY", nullptr));
        addBuildingState->setItemText(33, QCoreApplication::translate("MainWindow", "NC", nullptr));
        addBuildingState->setItemText(34, QCoreApplication::translate("MainWindow", "ND", nullptr));
        addBuildingState->setItemText(35, QCoreApplication::translate("MainWindow", "OH", nullptr));
        addBuildingState->setItemText(36, QCoreApplication::translate("MainWindow", "OK", nullptr));
        addBuildingState->setItemText(37, QCoreApplication::translate("MainWindow", "OR", nullptr));
        addBuildingState->setItemText(38, QCoreApplication::translate("MainWindow", "PA", nullptr));
        addBuildingState->setItemText(39, QCoreApplication::translate("MainWindow", "PR", nullptr));
        addBuildingState->setItemText(40, QCoreApplication::translate("MainWindow", "RI", nullptr));
        addBuildingState->setItemText(41, QCoreApplication::translate("MainWindow", "SC", nullptr));
        addBuildingState->setItemText(42, QCoreApplication::translate("MainWindow", "SD", nullptr));
        addBuildingState->setItemText(43, QCoreApplication::translate("MainWindow", "TN", nullptr));
        addBuildingState->setItemText(44, QCoreApplication::translate("MainWindow", "TX", nullptr));
        addBuildingState->setItemText(45, QCoreApplication::translate("MainWindow", "UT", nullptr));
        addBuildingState->setItemText(46, QCoreApplication::translate("MainWindow", "VT", nullptr));
        addBuildingState->setItemText(47, QCoreApplication::translate("MainWindow", "VA", nullptr));
        addBuildingState->setItemText(48, QCoreApplication::translate("MainWindow", "VI", nullptr));
        addBuildingState->setItemText(49, QCoreApplication::translate("MainWindow", "WA", nullptr));
        addBuildingState->setItemText(50, QCoreApplication::translate("MainWindow", "WV", nullptr));
        addBuildingState->setItemText(51, QCoreApplication::translate("MainWindow", "WI", nullptr));
        addBuildingState->setItemText(52, QCoreApplication::translate("MainWindow", "WY", nullptr));

        label_22->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Edit Building</span></p></body></html>", nullptr));
        buildingsBackButton_3->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Initial Gas Meter Reading</span></p></body></html>", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Initial Water Meter Reading</span></p></body></html>", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of Units</span></p></body></html>", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">State</span></p></body></html>", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Street Address</span></p></body></html>", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">City</span></p></body></html>", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Select Building</span></p></body></html>", nullptr));
        editBuildingsSaveButton->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        editBuildingState->setItemText(0, QCoreApplication::translate("MainWindow", "AL", nullptr));
        editBuildingState->setItemText(1, QCoreApplication::translate("MainWindow", "AK", nullptr));
        editBuildingState->setItemText(2, QCoreApplication::translate("MainWindow", "AZ", nullptr));
        editBuildingState->setItemText(3, QCoreApplication::translate("MainWindow", "AR", nullptr));
        editBuildingState->setItemText(4, QCoreApplication::translate("MainWindow", "CA", nullptr));
        editBuildingState->setItemText(5, QCoreApplication::translate("MainWindow", "CO", nullptr));
        editBuildingState->setItemText(6, QCoreApplication::translate("MainWindow", "CT", nullptr));
        editBuildingState->setItemText(7, QCoreApplication::translate("MainWindow", "DE", nullptr));
        editBuildingState->setItemText(8, QCoreApplication::translate("MainWindow", "DC", nullptr));
        editBuildingState->setItemText(9, QCoreApplication::translate("MainWindow", "FL", nullptr));
        editBuildingState->setItemText(10, QCoreApplication::translate("MainWindow", "GA", nullptr));
        editBuildingState->setItemText(11, QCoreApplication::translate("MainWindow", "HI", nullptr));
        editBuildingState->setItemText(12, QCoreApplication::translate("MainWindow", "ID", nullptr));
        editBuildingState->setItemText(13, QCoreApplication::translate("MainWindow", "IL", nullptr));
        editBuildingState->setItemText(14, QCoreApplication::translate("MainWindow", "IN", nullptr));
        editBuildingState->setItemText(15, QCoreApplication::translate("MainWindow", "IA", nullptr));
        editBuildingState->setItemText(16, QCoreApplication::translate("MainWindow", "KS", nullptr));
        editBuildingState->setItemText(17, QCoreApplication::translate("MainWindow", "KY", nullptr));
        editBuildingState->setItemText(18, QCoreApplication::translate("MainWindow", "LA", nullptr));
        editBuildingState->setItemText(19, QCoreApplication::translate("MainWindow", "ME", nullptr));
        editBuildingState->setItemText(20, QCoreApplication::translate("MainWindow", "MD", nullptr));
        editBuildingState->setItemText(21, QCoreApplication::translate("MainWindow", "MA", nullptr));
        editBuildingState->setItemText(22, QCoreApplication::translate("MainWindow", "MI", nullptr));
        editBuildingState->setItemText(23, QCoreApplication::translate("MainWindow", "MN", nullptr));
        editBuildingState->setItemText(24, QCoreApplication::translate("MainWindow", "MS", nullptr));
        editBuildingState->setItemText(25, QCoreApplication::translate("MainWindow", "MO", nullptr));
        editBuildingState->setItemText(26, QCoreApplication::translate("MainWindow", "MT", nullptr));
        editBuildingState->setItemText(27, QCoreApplication::translate("MainWindow", "NE", nullptr));
        editBuildingState->setItemText(28, QCoreApplication::translate("MainWindow", "NV", nullptr));
        editBuildingState->setItemText(29, QCoreApplication::translate("MainWindow", "NH", nullptr));
        editBuildingState->setItemText(30, QCoreApplication::translate("MainWindow", "NJ", nullptr));
        editBuildingState->setItemText(31, QCoreApplication::translate("MainWindow", "NM", nullptr));
        editBuildingState->setItemText(32, QCoreApplication::translate("MainWindow", "NY", nullptr));
        editBuildingState->setItemText(33, QCoreApplication::translate("MainWindow", "NC", nullptr));
        editBuildingState->setItemText(34, QCoreApplication::translate("MainWindow", "ND", nullptr));
        editBuildingState->setItemText(35, QCoreApplication::translate("MainWindow", "OH", nullptr));
        editBuildingState->setItemText(36, QCoreApplication::translate("MainWindow", "OK", nullptr));
        editBuildingState->setItemText(37, QCoreApplication::translate("MainWindow", "OR", nullptr));
        editBuildingState->setItemText(38, QCoreApplication::translate("MainWindow", "PA", nullptr));
        editBuildingState->setItemText(39, QCoreApplication::translate("MainWindow", "PR", nullptr));
        editBuildingState->setItemText(40, QCoreApplication::translate("MainWindow", "RI", nullptr));
        editBuildingState->setItemText(41, QCoreApplication::translate("MainWindow", "SC", nullptr));
        editBuildingState->setItemText(42, QCoreApplication::translate("MainWindow", "SD", nullptr));
        editBuildingState->setItemText(43, QCoreApplication::translate("MainWindow", "TN", nullptr));
        editBuildingState->setItemText(44, QCoreApplication::translate("MainWindow", "TX", nullptr));
        editBuildingState->setItemText(45, QCoreApplication::translate("MainWindow", "UT", nullptr));
        editBuildingState->setItemText(46, QCoreApplication::translate("MainWindow", "VT", nullptr));
        editBuildingState->setItemText(47, QCoreApplication::translate("MainWindow", "VA", nullptr));
        editBuildingState->setItemText(48, QCoreApplication::translate("MainWindow", "VI", nullptr));
        editBuildingState->setItemText(49, QCoreApplication::translate("MainWindow", "WA", nullptr));
        editBuildingState->setItemText(50, QCoreApplication::translate("MainWindow", "WV", nullptr));
        editBuildingState->setItemText(51, QCoreApplication::translate("MainWindow", "WI", nullptr));
        editBuildingState->setItemText(52, QCoreApplication::translate("MainWindow", "WY", nullptr));

        label_10->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Buildings</span></p></body></html>", nullptr));
        mainMenuButton1->setText(QCoreApplication::translate("MainWindow", "Main\n"
"Menu", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Reports</span></p></body></html>", nullptr));
        mainMenuButton2->setText(QCoreApplication::translate("MainWindow", "Main\n"
"Menu", nullptr));
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "Balance Sheet", nullptr));
        pushButton_10->setText(QCoreApplication::translate("MainWindow", "Receipts", nullptr));
        pushButton_18->setText(QCoreApplication::translate("MainWindow", "Collection List", nullptr));
        pushButton_14->setText(QCoreApplication::translate("MainWindow", "Vacancies", nullptr));
        pushButton_13->setText(QCoreApplication::translate("MainWindow", "Water by\n"
"Building", nullptr));
        pushButton_16->setText(QCoreApplication::translate("MainWindow", "Gas by\n"
"Building", nullptr));
        pushButton_12->setText(QCoreApplication::translate("MainWindow", "Rent by\n"
"Building", nullptr));
        pushButton_17->setText(QCoreApplication::translate("MainWindow", "Rent by\n"
"Tenant", nullptr));
        pushButton_15->setText(QCoreApplication::translate("MainWindow", "All Balances", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Select a Report to View and Print", nullptr));
        pushButton_11->setText(QCoreApplication::translate("MainWindow", "Current\n"
"Tenants", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Tenant Info</span></p></body></html>", nullptr));
        mainMenuButton3->setText(QCoreApplication::translate("MainWindow", "Main\n"
"Menu", nullptr));
        pushButton_21->setText(QCoreApplication::translate("MainWindow", "Past Tenants", nullptr));
        newTenantButton->setText(QCoreApplication::translate("MainWindow", "New Tenant", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Tenant Stats", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "Current Tenants", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "Everyone, Ever", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">New Tenant</span></p></body></html>", nullptr));
        tenantInfoBackButton1->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">First Name</span></p></body></html>", nullptr));
        newFirstName->setText(QString());
        label_35->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Last Name</span></p></body></html>", nullptr));
        newLastName->setText(QString());
        label_36->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Phone</span></p></body></html>", nullptr));
        newPhone->setText(QString());
        label_37->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Next of Kin</span></p></body></html>", nullptr));
        newNokName->setText(QString());
        label_38->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">NoK Relation</span></p></body></html>", nullptr));
        newNokRelation->setText(QString());
        label_39->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">NoK Phone</span></p></body></html>", nullptr));
        newNokPhone->setText(QString());
        label_40->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Building</span></p></body></html>", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Apartment</span></p></body></html>", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Employer</span></p></body></html>", nullptr));
        newEmployerPhone->setText(QString());
        label_43->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Employer Phone</span></p></body></html>", nullptr));
        newDeposit->setText(QString());
        label_44->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Deposit</span></p></body></html>", nullptr));
        newRent->setText(QString());
        label_45->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Rent</span></p></body></html>", nullptr));
        newEmployer->setText(QString());
        label_46->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Move-In Date</span></p></body></html>", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Due Day</span></p></body></html>", nullptr));
        newDueDayCombo->setItemText(0, QCoreApplication::translate("MainWindow", "Monday", nullptr));
        newDueDayCombo->setItemText(1, QCoreApplication::translate("MainWindow", "Tuesday", nullptr));
        newDueDayCombo->setItemText(2, QCoreApplication::translate("MainWindow", "Wednesday", nullptr));
        newDueDayCombo->setItemText(3, QCoreApplication::translate("MainWindow", "Thursday", nullptr));
        newDueDayCombo->setItemText(4, QCoreApplication::translate("MainWindow", "Friday", nullptr));
        newDueDayCombo->setItemText(5, QCoreApplication::translate("MainWindow", "Saturday", nullptr));
        newDueDayCombo->setItemText(6, QCoreApplication::translate("MainWindow", "Sunday", nullptr));
        newDueDayCombo->setItemText(7, QCoreApplication::translate("MainWindow", "(Monthly)", nullptr));

        label_48->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Notes</span></p></body></html>", nullptr));
        tenantInfoAddSubmit->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Frequency</span></p></body></html>", nullptr));
        newFreqCombo->setItemText(0, QCoreApplication::translate("MainWindow", "Weekly", nullptr));
        newFreqCombo->setItemText(1, QCoreApplication::translate("MainWindow", "Biweekly", nullptr));
        newFreqCombo->setItemText(2, QCoreApplication::translate("MainWindow", "Monthly", nullptr));

        newApartmentNum->setText(QString());
        label_8->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Utilities</span></p></body></html>", nullptr));
        mainMenuButton4->setText(QCoreApplication::translate("MainWindow", "Main\n"
"Menu", nullptr));
        pushButton_30->setText(QCoreApplication::translate("MainWindow", "Water Timeline", nullptr));
        pushButton_31->setText(QCoreApplication::translate("MainWindow", "Gas Timeline", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Resources Overview Current Week", nullptr));
        pushButton_27->setText(QCoreApplication::translate("MainWindow", "View Gas\n"
"Entries", nullptr));
        addWaterButton->setText(QCoreApplication::translate("MainWindow", "Add Water\n"
"Entry", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "Add Gas Entry", nullptr));
        pushButton_29->setText(QCoreApplication::translate("MainWindow", "View Water\n"
"Entries", nullptr));
        tenantInfoBackButton1_2->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        tenantInfoAddSubmit_2->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Water Reading</span></p></body></html>", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Reading</span></p></body></html>", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Building</span></p></body></html>", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Date</span></p></body></html>", nullptr));
        menumainwindow->setTitle(QCoreApplication::translate("MainWindow", "Settings", nullptr));
        menuHelp->setTitle(QCoreApplication::translate("MainWindow", "Help", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
